use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum BonusTrigger {
    AbilitySlotted,
    AbilitySlottedCount,
    ArcanistCrux,
    BowEquipped,
    BurningOrPoisonDamageDealt,
    Cast,
    CriticalDamageDealt,
    DestructionStuffEquipped,
    DualWieldAxeEquipped,
    DualWieldDaggerEquipped,
    DualWieldEquipped,
    DualWieldMaceEquipped,
    DualWieldSwordEquipped,
    EnemyBurning,
    EnemyChilled,
    EnemyHasStatusEffect,
    EnemyOffBalance,
    EnemyPoisoned,
    Flanking,
    IceStaffEquipped,
    InfernoStaffEquipped,
    LightningStaffEquipped,
    MagickaOrStaminaRestored,
    Passive,
    SkillLineSkillCast,
    SkillLineSlotted,
    TwoHandedAxeEquipped,
    TwoHandedEquipped,
    TwoHandedMaceEquipped,
    TwoHandedSwordEquipped,
}
