use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum BonusTarget {
    AoeDamage,
    BurningAndPoisonDamage,
    ChilledStatusEffectChance,
    ChilledStatusEffectDamage,
    CriticalChance,
    CriticalDamage,
    Damage,
    DirectDamage,
    DotDamage,
    DurationSkillLineFlat,
    DurationSkillLineMultiplier,
    EnemyDamageTaken,
    EnemyResistanceReduction,
    FlameDamage,
    FrostDamage,
    HeavyAttackDamage,
    MaxMagicka,
    MaxStamina,
    OffBalanceDamage,
    PhysicalAndSpellPenetration,
    PhysicalDamage,
    RestoreMagickaOrStamina,
    ShockDamage,
    SingleDamage,
    SpellCriticalChance,
    SpellDamage,
    StatusEffectChance,
    StatusEffectDamage,
    WeaponAndSpellDamageFlat,
    WeaponAndSpellDamageMultiplier,
    WeaponCriticalChance,
    WeaponDamage,
}
