// Auto-generated by datamine/generate_passives_rs.py — do not edit manually.
// Manual overrides (bonuses) stored in generator script.
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, ClassName, PassiveData,
    SkillLineName,
};
use once_cell::sync::Lazy;

pub static TWO_HANDED_PASSIVES: Lazy<Vec<PassiveData>> = Lazy::new(|| {
    vec![
        PassiveData::new(
            "Balanced Blade",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            vec![],
        )
        .with_skill_id(45443),
        PassiveData::new(
            "Battle Rush",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            vec![],
        )
        .with_skill_id(45448),
        PassiveData::new(
            "Follow Up",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            vec![], // TODO: Requires Heavy Attack tracking to implement,
        )
        .with_skill_id(45446),
        PassiveData::new(
            "Forceful",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            vec![],
        )
        .with_skill_id(45444),
        PassiveData::new(
            "Heavy Weapons",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            vec![BonusData::new(
                "Heavy Weapons",
                BonusSource::Passive,
                BonusTrigger::TwoHandedEquipped,
                BonusValue::new(
                    "Heavy Weapons (Sword)",
                    BonusTarget::WeaponAndSpellDamageFlat,
                    258.0,
                ),
            )
            .with_alternative(BonusValue::new(
                "Heavy Weapons (Axe)",
                BonusTarget::CriticalDamage,
                0.12,
            ))
            .with_alternative(BonusValue::new(
                "Heavy Weapons (Mace)",
                BonusTarget::PhysicalAndSpellPenetration,
                2974.0,
            ))],
        )
        .with_skill_id(45430),
    ]
});
