// Auto-generated by datamine/generate_skills_rs.py — do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::unique::{EMPOWER, MAJOR_BERSERK, MAJOR_BRUTALITY, MAJOR_SORCERY};
use crate::domain::{
    ClassName, DamageFlags, DotDamage, ExecuteScaling, HitDamage, Resource, SkillDamage, SkillData,
    SkillLineName,
};
use once_cell::sync::Lazy;

pub static TWO_HANDED_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Berserker Rage",
            "Berserker Strike",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Ultimate,
        )
        .with_skill_id(86295)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.15495,
            1.62698,
        )])),
        SkillData::new(
            "Berserker Strike",
            "Berserker Strike",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Ultimate,
        )
        .with_skill_id(86275)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.15,
            1.575,
        )])),
        SkillData::new(
            "Brawler",
            "Cleave",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39769)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.81349,
        )])),
        SkillData::new(
            "Carve",
            "Cleave",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39754)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::BLEED | DamageFlags::AOE | DamageFlags::MELEE,
                    0.077475,
                    0.81349,
                )])
                .with_dots(vec![DotDamage::new(
                    6.0,
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
                    0.127746,
                    1.3478,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Cleave",
            "Cleave",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39746)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.075,
            0.7875,
        )])),
        SkillData::new(
            "Critical Charge",
            "Critical Charge",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39793)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.06,
            0.63,
        )])),
        SkillData::new(
            "Critical Rush",
            "Critical Charge",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39822)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.06198,
            0.65079,
        )])),
        SkillData::new(
            "Dizzying Swing",
            "Uppercut",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39984)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.118795,
            1.24735,
        )]))
        .with_spammable(),
        SkillData::new(
            "Executioner",
            "Reverse Slash",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39957)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::BLEED | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.05165,
            0.54233,
        )]))
        .with_spammable()
        .with_execute(4.0, 0.5, ExecuteScaling::Linear),
        SkillData::new(
            "Forward Momentum",
            "Momentum",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39892)
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone().with_duration(40.0),
            MAJOR_SORCERY.clone().with_duration(40.0),
        ]),
        SkillData::new(
            "Immobilizing Smash",
            "Immobilizing Smash",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Magicka,
        )
        .with_skill_id(40217190),
        SkillData::new(
            "Momentum",
            "Momentum",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39881)
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
        SkillData::new(
            "Onslaught",
            "Berserker Strike",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Ultimate,
        )
        .with_skill_id(86284)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.15495,
            1.62698,
        )])),
        SkillData::new(
            "Rally",
            "Momentum",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39904)
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
        SkillData::new(
            "Reverse Slash",
            "Reverse Slash",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39928)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.05,
            0.525,
        )]))
        .with_spammable()
        .with_execute(3.0, 0.5, ExecuteScaling::Linear),
        SkillData::new(
            "Reverse Slice",
            "Reverse Slash",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39942)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.05165,
            0.54233,
        )]))
        .with_spammable()
        .with_execute(3.0, 0.5, ExecuteScaling::Linear),
        SkillData::new(
            "Stampede",
            "Critical Charge",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39807)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
                    0.06198,
                    0.65079,
                )])
                .with_dots(vec![DotDamage::new(
                    15.0,
                    DamageFlags::PHYSICAL | DamageFlags::AOE,
                    0.013773,
                    0.14462,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Uppercut",
            "Uppercut",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(39968)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.115,
            1.2075,
        )]))
        .with_spammable(),
        SkillData::new(
            "Wrecking Blow",
            "Uppercut",
            ClassName::Weapon,
            SkillLineName::TwoHanded,
            Resource::Stamina,
        )
        .with_skill_id(40008)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.118795,
            1.24735,
        )]))
        .with_spammable()
        .with_bonuses(vec![
            EMPOWER.clone().with_duration(3.0),
            MAJOR_BERSERK.clone().with_duration(3.0),
        ]),
    ]
});
