// Auto-generated by datamine/generate_skills_rs.py - do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::unique::{MAJOR_PROPHECY, MAJOR_SAVAGERY, MINOR_BERSERK, MINOR_FORCE};
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, SkillTree, DamageFlags,
    DotDamage, HitDamage, Resource, SkillDamage, SkillData, SkillLineName,
};
use once_cell::sync::Lazy;

pub static FIGHTERS_GUILD_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Barbed Trap",
            "Trap Beast",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42747)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
                    0.06198,
                    0.65079,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
                    0.015495,
                    0.162697,
                )
                .with_interval(2.0)]),
        )
        .with_bonuses(vec![MINOR_FORCE.clone()]),
        SkillData::new(
            "Camouflaged Hunter",
            "Expert Hunter",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42641)
        .with_bonuses(vec![
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MINOR_BERSERK.clone().with_duration(5.0),
        ]),
        SkillData::new(
            "Circle of Protection",
            "Circle of Protection",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42509),
        SkillData::new(
            "Dawnbreaker",
            "Dawnbreaker",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Ultimate,
        )
        .with_skill_id(42566)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
                    0.125,
                    1.3125,
                )])
                .with_dots(vec![DotDamage::new(
                    4.0,
                    DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
                    0.05,
                    0.525,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Dawnbreaker of Smiting",
            "Dawnbreaker",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Ultimate,
        )
        .with_skill_id(42598)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
                    0.15495,
                    1.62698,
                )])
                .with_dots(vec![DotDamage::new(
                    4.0,
                    DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
                    0.06198,
                    0.65079,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Evil Hunter",
            "Expert Hunter",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42624)
        .with_bonuses(vec![
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Expert Hunter",
            "Expert Hunter",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42610)
        .with_bonuses(vec![
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Flawless Dawnbreaker",
            "Dawnbreaker",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Ultimate,
        )
        .with_skill_id(42586)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
                    0.129125,
                    1.35581,
                )])
                .with_dots(vec![DotDamage::new(
                    4.0,
                    DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
                    0.05165,
                    0.542325,
                )
                .with_interval(2.0)]),
        )
        .with_bonuses(vec![BonusData::new(
            "Flawless Dawnbreaker",
            BonusSource::Buff,
            BonusTrigger::Cast,
            BonusValue::new(
                "Flawless Dawnbreaker",
                BonusTarget::WeaponAndSpellDamageFlat,
                300.0,
            ),
        )
        .with_duration(20.0)]),
        SkillData::new(
            "Lightweight Beast Trap",
            "Trap Beast",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42771)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                    0.05165,
                    0.542325,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
                    0.015495,
                    0.162697,
                )
                .with_interval(2.0)]),
        )
        .with_bonuses(vec![MINOR_FORCE.clone()]),
        SkillData::new(
            "Ring of Preservation",
            "Ring of Preservation",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42548),
        SkillData::new(
            "Silver Bolts",
            "Silver Bolts",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42655)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.09,
            0.945,
        )])),
        SkillData::new(
            "Silver Leash",
            "Silver Bolts",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42696)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.06198,
            0.65079,
        )])),
        SkillData::new(
            "Silver Shards",
            "Silver Bolts",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42671)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE,
            0.09297,
            0.976185,
        )])),
        SkillData::new(
            "Trap Beast",
            "Trap Beast",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42720)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                    0.05,
                    0.525,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
                    0.015,
                    0.1575,
                )
                .with_interval(2.0)]),
        )
        .with_bonuses(vec![MINOR_FORCE.clone()]),
        SkillData::new(
            "Turn Evil",
            "Turn Evil",
            SkillTree::Guild,
            SkillLineName::FightersGuild,
            Resource::Stamina,
        )
        .with_skill_id(42529),
    ]
});
