// Auto-generated by datamine/generate_passives_rs.py — do not edit manually.
// Manual overrides (bonuses) stored in generator script.
use crate::domain::{BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, ClassName, PassiveData, SkillLineName};
use once_cell::sync::Lazy;

pub static FIGHTERS_GUILD_PASSIVES: Lazy<Vec<PassiveData>> = Lazy::new(|| {
    vec![
        PassiveData::new(
            "Banish the Wicked",
            ClassName::Guild,
            SkillLineName::FightersGuild,
            vec![],
        )
            .with_skill_id(45599),
        PassiveData::new(
            "Intimidating Presence",
            ClassName::Guild,
            SkillLineName::FightersGuild,
            vec![],
        )
            .with_skill_id(29062),
        PassiveData::new(
            "Skilled Tracker",
            ClassName::Guild,
            SkillLineName::FightersGuild,
            vec![BonusData::new(
                "Skilled Tracker",
                BonusSource::Passive,
                BonusTrigger::Passive,
                BonusValue::new("Skilled Tracker", BonusTarget::Damage, 0.10),
            )
            .with_skill_line_filter(SkillLineName::FightersGuild)],
        )
            .with_skill_id(40393),
        PassiveData::new(
            "Slayer",
            ClassName::Guild,
            SkillLineName::FightersGuild,
            vec![BonusData::new(
                "Slayer",
                BonusSource::Passive,
                BonusTrigger::AbilitySlottedCount,
                BonusValue::new(
                    "Slayer",
                    BonusTarget::WeaponAndSpellDamageMultiplier,
                    0.03,
                ),
            )
            .with_skill_line_filter(SkillLineName::FightersGuild)],
        )
            .with_skill_id(45596),
    ]
});
