// Auto-generated by datamine/generate_passives_rs.py - do not edit manually.
// Manual overrides (bonuses) stored in generator script.
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, PassiveData, SkillLineName,
    SkillTree,
};
use once_cell::sync::Lazy;

pub static DESTRUCTION_STAFF_PASSIVES: Lazy<Vec<PassiveData>> = Lazy::new(|| {
    vec![
        PassiveData::new(
            "Ancient Knowledge",
            SkillTree::Weapon,
            SkillLineName::DestructionStaff,
            vec![BonusData::new(
                "Ancient Knowledge (Inferno)",
                BonusSource::Passive,
                BonusTrigger::DestructionStuffEquipped,
                BonusValue::new("Ancient Knowledge (Inferno)", BonusTarget::DotDamage, 0.12),
            )
            .with_alternative(BonusValue::new(
                "Ancient Knowledge (Lightning)",
                BonusTarget::DirectDamage,
                0.12,
            ))],
        )
        .with_skill_id(45513),
        PassiveData::new(
            "Destruction Expert",
            SkillTree::Weapon,
            SkillLineName::DestructionStaff,
            vec![], // Not tracked - resource recovery on kill,
        )
        .with_skill_id(45514),
        PassiveData::new(
            "Elemental Force",
            SkillTree::Weapon,
            SkillLineName::DestructionStaff,
            vec![BonusData::new(
                "Elemental Force",
                BonusSource::Passive,
                BonusTrigger::DestructionStuffEquipped,
                BonusValue::new("Elemental Force", BonusTarget::StatusEffectChance, 1.0),
            )],
        )
        .with_skill_id(45512),
        PassiveData::new(
            "Penetrating Magic",
            SkillTree::Weapon,
            SkillLineName::DestructionStaff,
            vec![BonusData::new(
                "Penetrating Magic",
                BonusSource::Passive,
                BonusTrigger::DestructionStuffEquipped,
                BonusValue::new(
                    "Penetrating Magic",
                    BonusTarget::PhysicalAndSpellPenetration,
                    2974.0,
                ),
            )
            .with_skill_line_filter(SkillLineName::Bow)],
        )
        .with_skill_id(45509),
        PassiveData::new(
            "Tri Focus",
            SkillTree::Weapon,
            SkillLineName::DestructionStaff,
            vec![], // TODO: Requires HA mechanic,
        )
        .with_skill_id(45500),
    ]
});
