// Auto-generated by datamine/generate_skills_rs.py - do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::unique::MAJOR_BREACH;
use crate::domain::{
    ClassName, DamageFlags, DotDamage, HitDamage, Resource, SkillDamage, SkillData, SkillLineName,
};
use once_cell::sync::Lazy;

pub static DESTRUCTION_STAFF_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Crushing Shock",
            "Force Shock",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(48971)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
                0.03099,
                0.325395,
            ),
            HitDamage::new(
                DamageFlags::FROST | DamageFlags::SINGLE_TARGET,
                0.03099,
                0.325395,
            ),
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET,
                0.03099,
                0.325395,
            ),
        ]))
        .with_spammable(),
        SkillData::new(
            "Destructive Clench",
            "Destructive Touch",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(41006)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.05165,
            0.542325,
        )])),
        SkillData::new(
            "Destructive Reach",
            "Destructive Touch",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(41047)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                    0.05165,
                    0.542325,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
                    0.015495,
                    0.162697,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Destructive Touch",
            "Destructive Touch",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(40964)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                    0.05,
                    0.525,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                    0.015,
                    0.1575,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Elemental Blockade",
            "Wall of Elements",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(41769)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            12.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.012521,
            0.131473,
        ).with_interval(1.0)])),
        SkillData::new(
            "Elemental Drain",
            "Weakness to Elements",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(41567)
        .with_bonuses(vec![MAJOR_BREACH.clone().with_duration(60.0)]),
        SkillData::new(
            "Elemental Rage",
            "Elemental Storm",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Ultimate,
        )
        .with_skill_id(86510)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            7.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.09685,
            1.0169,
        ).with_interval(1.0)])),
        SkillData::new(
            "Elemental Ring",
            "Impulse",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(42975)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        )]))
        .with_spammable(),
        SkillData::new(
            "Elemental Storm",
            "Elemental Storm",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Ultimate,
        )
        .with_skill_id(86485)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            7.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.075,
            0.7875,
        ).with_interval(1.0)])),
        SkillData::new(
            "Elemental Susceptibility",
            "Weakness to Elements",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(41556)
        .with_bonuses(vec![MAJOR_BREACH.clone().with_duration(30.0)]),
        SkillData::new(
            "Eye of the Storm",
            "Elemental Storm",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Ultimate,
        )
        .with_skill_id(86534)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            7.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.07748,
            0.81349,
        ).with_interval(1.0)])),
        SkillData::new(
            "Force Pulse",
            "Force Shock",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(48991)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
                0.03099,
                0.325395,
            ),
            HitDamage::new(
                DamageFlags::FROST | DamageFlags::SINGLE_TARGET,
                0.03099,
                0.325395,
            ),
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET,
                0.03099,
                0.325395,
            ),
            HitDamage::new(
                DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                0.1033,
                1.08465,
            ),
        ]))
        .with_spammable(),
        SkillData::new(
            "Force Shock",
            "Force Shock",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(48956)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::FLAME | DamageFlags::SINGLE_TARGET, 0.03, 0.315),
            HitDamage::new(DamageFlags::FROST | DamageFlags::SINGLE_TARGET, 0.03, 0.315),
            HitDamage::new(DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET, 0.03, 0.315),
        ]))
        .with_spammable(),
        SkillData::new(
            "Impulse",
            "Impulse",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(42957)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.075,
            0.7875,
        )]))
        .with_spammable(),
        SkillData::new(
            "Pulsar",
            "Impulse",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(42996)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.077475,
            0.813488,
        )]))
        .with_spammable(),
        SkillData::new(
            "Unstable Wall of Elements",
            "Wall of Elements",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(41711)
        .with_damage(
            SkillDamage::new()
                .with_dots(vec![DotDamage::new(
                    8.0,
                    DamageFlags::magic_aoe(),
                    0.012521,
                    0.131473,
                )
                .with_interval(1.0)])
                .with_hits(vec![HitDamage::new(
                    DamageFlags::magic_aoe(),
                    0.05165,
                    0.542325,
                )
                .with_delay(8.0)]),
        ),
        SkillData::new(
            "Wall of Elements",
            "Wall of Elements",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(41658)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.012121,
            0.127273,
        ).with_interval(1.0)])),
        SkillData::new(
            "Weakness to Elements",
            "Weakness to Elements",
            ClassName::Weapon,
            SkillLineName::DestructionStaff,
            Resource::Magicka,
        )
        .with_skill_id(41548)
        .with_bonuses(vec![MAJOR_BREACH.clone().with_duration(30.0)]),
    ]
});
