// Auto-generated by datamine/generate_skills_rs.py — do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::{
    EMPOWER, MAJOR_BREACH, MAJOR_BRUTALITY, MAJOR_SORCERY,
};
use crate::domain::{
    ClassName, DamageFlags, DotDamage, HitDamage, Resource, SkillDamage, SkillData, SkillLineName,
};
use once_cell::sync::Lazy;

pub static TEMPLAR_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Aurora Javelin",
            "Piercing Javelin",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(26983)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.06198,
            0.65079,
        )])),
        SkillData::new(
            "Binding Javelin",
            "Piercing Javelin",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Stamina,
        )
        .with_skill_id(26992)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.06198,
            0.65079,
        )])),
        SkillData::new(
            "Biting Jabs",
            "Puncturing Strikes",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Stamina,
        )
        .with_skill_id(27197)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.039598,
            0.415783,
        )]))
        .with_channel_time(0.8)
        .with_bonuses(vec![MAJOR_BRUTALITY.clone().with_duration(10.0), MAJOR_SORCERY.clone().with_duration(10.0)]),
        SkillData::new(
            "Blazing Shield",
            "Sun Shield",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(27530),
        SkillData::new(
            "Blazing Spear",
            "Spear Shards",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(27167)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        )])
            .with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.011948,
            0.125458,
        ).with_interval(1.0)])),
        SkillData::new(
            "Crescent Sweep",
            "Radial Sweep",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Ultimate,
        )
        .with_skill_id(23788)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.1033,
            1.08465,
        )])
            .with_dots(vec![DotDamage::new(
            6.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.05165,
            0.54233,
        ).with_interval(2.0)])),
        SkillData::new(
            "Everlasting Sweep",
            "Radial Sweep",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Ultimate,
        )
        .with_skill_id(23794)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.1033,
            1.08465,
        )])
            .with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::PHYSICAL | DamageFlags::AOE,
            0.05165,
            0.54233,
        ).with_interval(2.0)])),
        SkillData::new(
            "Explosive Charge",
            "Focused Charge",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(23726)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        )])),
        SkillData::new(
            "Focused Charge",
            "Focused Charge",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(23716)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.06,
            0.63,
        )])),
        SkillData::new(
            "Luminous Shards",
            "Spear Shards",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(27122)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        )])
            .with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.007403,
            0.077733,
        ).with_interval(1.0)])),
        SkillData::new(
            "Piercing Javelin",
            "Piercing Javelin",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(26975)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.06,
            0.63,
        )])),
        SkillData::new(
            "Puncturing Strikes",
            "Puncturing Strikes",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(27186)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.038333,
            0.4025,
        )]))
        .with_channel_time(0.8),
        SkillData::new(
            "Puncturing Sweep",
            "Puncturing Strikes",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(27207)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.039598,
            0.415783,
        )]))
        .with_channel_time(0.8),
        SkillData::new(
            "Radial Sweep",
            "Radial Sweep",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Ultimate,
        )
        .with_skill_id(23784)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.1,
            1.05,
        )])
            .with_dots(vec![DotDamage::new(
            6.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.05,
            0.525,
        ).with_interval(2.0)])),
        SkillData::new(
            "Radiant Ward",
            "Sun Shield",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(27514)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        )])),
        SkillData::new(
            "Spear Shards",
            "Spear Shards",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(27090)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.075,
            0.7875,
        )])
            .with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.007167,
            0.07525,
        ).with_interval(1.0)])),
        SkillData::new(
            "Sun Shield",
            "Sun Shield",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(27501)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.075,
            0.7875,
        )])),
        SkillData::new(
            "Toppling Charge",
            "Focused Charge",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            Resource::Magicka,
        )
        .with_skill_id(23870)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.06198,
            0.65079,
        )])),
        SkillData::new(
            "Backlash",
            "Backlash",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(27227)
        .with_damage(
            SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_single(), 0.05, 0.525),
            HitDamage::new(DamageFlags::magic_single(), 0.055333, 0.581).with_delay(6.0),
        ])),
        SkillData::new(
            "Dark Flare",
            "Solar Flare",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(24147)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.106915,
            1.12261,
        )]))
        .with_spammable()
        .with_bonuses(vec![EMPOWER.clone()]),
        SkillData::new(
            "Eclipse",
            "Eclipse",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(27306),
        SkillData::new(
            "Living Dark",
            "Eclipse",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(27324),
        SkillData::new(
            "Nova",
            "Nova",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Ultimate,
        )
        .with_skill_id(24063)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.1159,
            1.217,
        )])
            .with_dots(vec![DotDamage::new(
            8.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.05,
            0.525,
        ).with_interval(1.0)])),
        SkillData::new(
            "Power of the Light",
            "Backlash",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Stamina,
        )
        .with_skill_id(27587)
        .with_damage(
            SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::physical_single(), 0.05165, 0.542325),
            HitDamage::new(DamageFlags::physical_single(), 0.057159, 0.600173).with_delay(6.0),
        ]))
        .with_bonuses(vec![MAJOR_BREACH.clone()]),
        SkillData::new(
            "Purifying Light",
            "Backlash",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(27558)
        .with_damage(
            SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_single(), 0.05165, 0.54233),
            HitDamage::new(DamageFlags::magic_single(), 0.057159, 0.600173).with_delay(6.0),
        ])),
        SkillData::new(
            "Radiant Destruction",
            "Radiant Destruction",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(63058)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.0537712,
            0.56345,
        )]))
        .with_channel_time(3.8),
        SkillData::new(
            "Radiant Glory",
            "Radiant Destruction",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(63066)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.0555417,
            0.582282,
        )]))
        .with_channel_time(3.8),
        SkillData::new(
            "Radiant Oppression",
            "Radiant Destruction",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(63075)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.0555417,
            0.582282,
        )]))
        .with_channel_time(3.8),
        SkillData::new(
            "Reflective Light",
            "Sun Fire",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(24195)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::AOE,
            0.05165,
            0.542325,
        )])
            .with_dots(vec![DotDamage::new(
            18.0,
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.015495,
            0.162697,
        ).with_interval(2.0)])),
        SkillData::new(
            "Solar Barrage",
            "Solar Flare",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(24157)
        .with_damage(
            SkillDamage::new()
            .with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.018782,
            0.19721,
        ).with_interval(2.0)]))
        .with_bonuses(vec![EMPOWER.clone().with_duration(20.0)]),
        SkillData::new(
            "Solar Disturbance",
            "Nova",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Ultimate,
        )
        .with_skill_id(24320)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.1159,
            1.217,
        )])
            .with_dots(vec![DotDamage::new(
            8.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.05165,
            0.54233,
        ).with_interval(1.0)])),
        SkillData::new(
            "Solar Flare",
            "Solar Flare",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(24110)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.1035,
            1.08675,
        )]))
        .with_spammable()
        .with_bonuses(vec![EMPOWER.clone()]),
        SkillData::new(
            "Solar Prison",
            "Nova",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Ultimate,
        )
        .with_skill_id(24301)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.231809,
            2.434,
        )])
            .with_dots(vec![DotDamage::new(
            8.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.05165,
            0.54233,
        ).with_interval(1.0)])),
        SkillData::new(
            "Sun Fire",
            "Sun Fire",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(24171)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.05,
            0.525,
        )])
            .with_dots(vec![DotDamage::new(
            18.0,
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.015,
            0.1575,
        ).with_interval(2.0)])),
        SkillData::new(
            "Unstable Core",
            "Eclipse",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(27311)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![
        HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.019369,
            0.203372,
        ),
        HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.038738,
            0.406744,
        ),
        HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        ),
        ])),
        SkillData::new(
            "Vampire's Bane",
            "Sun Fire",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            Resource::Magicka,
        )
        .with_skill_id(24180)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.05165,
            0.542325,
        )])
            .with_dots(vec![DotDamage::new(
            28.0,
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.015495,
            0.162697,
        ).with_interval(2.0)])),
        SkillData::new(
            "Breath of Life",
            "Rushed Ceremony",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(24222),
        SkillData::new(
            "Channeled Focus",
            "Rune Focus",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(23998),
        SkillData::new(
            "Cleansing Ritual",
            "Cleansing Ritual",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(27255),
        SkillData::new(
            "Extended Ritual",
            "Cleansing Ritual",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(27295),
        SkillData::new(
            "Hasty Prayer",
            "Healing Ritual",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(27376),
        SkillData::new(
            "Healing Ritual",
            "Healing Ritual",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(27342),
        SkillData::new(
            "Honor the Dead",
            "Rushed Ceremony",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(24213),
        SkillData::new(
            "Practiced Incantation",
            "Rite of Passage",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Ultimate,
        )
        .with_skill_id(27427)
        .with_channel_time(8.0),
        SkillData::new(
            "Radiant Aura",
            "Restoring Aura",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(27030),
        SkillData::new(
            "Remembrance",
            "Rite of Passage",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Ultimate,
        )
        .with_skill_id(27413)
        .with_channel_time(4.0),
        SkillData::new(
            "Repentance",
            "Restoring Aura",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(27043),
        SkillData::new(
            "Restoring Aura",
            "Restoring Aura",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(27007),
        SkillData::new(
            "Restoring Focus",
            "Rune Focus",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Stamina,
        )
        .with_skill_id(23985),
        SkillData::new(
            "Rite of Passage",
            "Rite of Passage",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Ultimate,
        )
        .with_skill_id(27396)
        .with_channel_time(4.0),
        SkillData::new(
            "Ritual of Rebirth",
            "Healing Ritual",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(27352),
        SkillData::new(
            "Ritual of Retribution",
            "Cleansing Ritual",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(27275)
        .with_damage(
            SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::magic_aoe(),
            0.018782,
            0.19721,
        )
        .with_interval(2.0)
        .with_increase_per_tick(0.12)])),
        SkillData::new(
            "Rune Focus",
            "Rune Focus",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(23970),
        SkillData::new(
            "Rushed Ceremony",
            "Rushed Ceremony",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            Resource::Magicka,
        )
        .with_skill_id(24204),
    ]
});
