// Auto-generated by datamine/generate_passives_rs.py - do not edit manually.
// Manual overrides (bonuses) stored in generator script.
use crate::data::bonuses::{MINOR_BERSERK, MINOR_SORCERY};
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, ClassName, PassiveData,
    SkillLineName,
};
use once_cell::sync::Lazy;

pub static TEMPLAR_PASSIVES: Lazy<Vec<PassiveData>> = Lazy::new(|| {
    vec![
        PassiveData::new(
            "Balanced Warrior",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            vec![BonusData::new(
                "Balanced Warrior",
                BonusSource::Passive,
                BonusTrigger::SkillLineSlotted,
                BonusValue::new(
                    "Balanced Warrior",
                    BonusTarget::WeaponAndSpellDamageMultiplier,
                    0.06,
                ),
            )],
        )
        .with_skill_id(44732),
        PassiveData::new(
            "Burning Light",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            vec![], // TODO: To complex, stacks + consume for trigger damage,
        )
        .with_skill_id(44730),
        PassiveData::new(
            "Piercing Spear",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            vec![BonusData::new(
                "Piercing Spear",
                BonusSource::Passive,
                BonusTrigger::AbilitySlotted,
                BonusValue::new("Piercing Spear", BonusTarget::CriticalDamage, 0.12),
            )],
        )
        .with_skill_id(44046),
        PassiveData::new(
            "Spear Wall",
            ClassName::Templar,
            SkillLineName::AedricSpear,
            vec![MINOR_BERSERK
                .clone()
                .with_trigger(BonusTrigger::SkillLineSkillCast)
                .with_duration(6.0)],
        )
        .with_skill_id(44721),
        PassiveData::new(
            "Enduring Rays",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            vec![], // TODO: duration increase to specific skills,
        )
        .with_skill_id(45214),
        PassiveData::new(
            "Illuminate",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            vec![MINOR_SORCERY
                .clone()
                .with_trigger(BonusTrigger::SkillLineSkillCast)],
        )
        .with_skill_id(45215),
        PassiveData::new(
            "Prism",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            vec![], // TODO: generates 3 ultimate,
        )
        .with_skill_id(45216),
        PassiveData::new(
            "Restoring Spirit",
            ClassName::Templar,
            SkillLineName::DawnsWrath,
            vec![],
        )
        .with_skill_id(45212),
        PassiveData::new(
            "Light Weaver",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            vec![],
        )
        .with_skill_id(45208),
        PassiveData::new(
            "Master Ritualist",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            vec![],
        )
        .with_skill_id(45202),
        PassiveData::new(
            "Mending",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            vec![],
        )
        .with_skill_id(45206),
        PassiveData::new(
            "Sacred Ground",
            ClassName::Templar,
            SkillLineName::RestoringLight,
            vec![],
        )
        .with_skill_id(45207),
    ]
});
