#!/usr/bin/env python3
"""Generate Rust set data files from extracted sets.json.

Reads datamine/sets.json and overwrites:
  - src/data/sets/normal.rs
  - src/data/sets/monster.rs
  - src/data/sets/mythic.rs
  - src/data/sets/arena.rs

Only DPS-relevant stat bonuses are mapped. Complex/proc/conditional bonuses
are skipped (threshold omitted entirely if no mappable bonuses).
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

# Stat name -> (BonusTarget variant, display name for BonusValue)
STAT_MAP = {
    "Maximum Magicka": ("MaxMagickaFlat", "Max Magicka"),
    "Maximum Stamina": ("MaxStaminaFlat", "Max Stamina"),
    "Critical Chance": ("CriticalRating", "Critical Chance"),
    "Weapon and Spell Damage": ("WeaponAndSpellDamageFlat", "Weapon and Spell Damage"),
    "Offensive Penetration": ("PhysicalAndSpellPenetration", "Offensive Penetration"),
}

# set_type -> (filename, static name)
FILE_MAP = {
    "Normal": ("normal.rs", "NORMAL_SETS"),
    "Monster": ("monster.rs", "MONSTER_SETS"),
    "Mythic": ("mythic.rs", "MYTHIC_SETS"),
    "Arena": ("arena.rs", "ARENA_SETS"),
}

HEADER_WITH_BONUS = """\
// Auto-generated by datamine/generate_sets_rs.py — do not edit manually.
use crate::domain::{{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, SetData, SetType,
}};
use once_cell::sync::Lazy;
"""

HEADER_NO_BONUS = """\
// Auto-generated by datamine/generate_sets_rs.py — do not edit manually.
use crate::domain::{{SetData, SetType}};
use once_cell::sync::Lazy;
"""


def escape_rust_str(s: str) -> str:
    """Escape a string for use inside a Rust string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def is_mappable(bonus: dict) -> bool:
    """Check if a bonus can be mapped to a BonusTarget."""
    if bonus.get("bonus_type") != "stat":
        return False
    stat = bonus.get("stat_name", "")
    # Skip conditional stats (contain " to your ")
    if " to your " in stat:
        return False
    return stat in STAT_MAP


def generate_bonus_data(set_name: str, pc: int, bonus: dict) -> str | None:
    """Generate a BonusData::new(...) call for a single bonus, or None if unmappable."""
    if not is_mappable(bonus):
        return None

    stat = bonus["stat_name"]
    target_variant, display = STAT_MAP[stat]
    value = float(bonus["value"])
    escaped_name = escape_rust_str(set_name)

    return (
        f'BonusData::new(\n'
        f'                    "{escaped_name} {pc}pc",\n'
        f'                    BonusSource::GearSet,\n'
        f'                    BonusTrigger::Passive,\n'
        f'                    BonusValue::new("{display}", BonusTarget::{target_variant}, {value:.1f}),\n'
        f'                )'
    )


def generate_set(set_data: dict) -> str:
    """Generate the Rust code for a single SetData entry."""
    name = set_data["name"]
    set_type = set_data["set_type"]
    escaped_name = escape_rust_str(name)

    # Group bonuses by piece_count
    by_pc: dict[int, list[dict]] = defaultdict(list)
    for bonus in set_data["bonuses"]:
        by_pc[bonus["piece_count"]].append(bonus)

    # Build threshold chains
    thresholds = []
    for pc in sorted(by_pc.keys()):
        bonus_codes = []
        for bonus in by_pc[pc]:
            code = generate_bonus_data(name, pc, bonus)
            if code is not None:
                bonus_codes.append(code)

        if not bonus_codes:
            continue

        if len(bonus_codes) == 1:
            bonuses_str = f"vec![{bonus_codes[0]}]"
        else:
            items = ",\n                ".join(bonus_codes)
            bonuses_str = f"vec![\n                {items},\n            ]"

        thresholds.append(
            f".with_threshold(\n"
            f"            {pc},\n"
            f"            {bonuses_str},\n"
            f"        )"
        )

    # Build the full set expression
    lines = f'SetData::new("{escaped_name}", SetType::{set_type})'
    for t in thresholds:
        lines += f"\n        {t}"

    return lines


def generate_file(sets: list[dict], static_name: str) -> str:
    """Generate the full Rust source file for a set category."""
    has_any_bonus = any(
        is_mappable(b) for s in sets for b in s["bonuses"]
    )
    lines = [HEADER_WITH_BONUS if has_any_bonus else HEADER_NO_BONUS]
    lines.append(f"pub static {static_name}: Lazy<Vec<SetData>> = Lazy::new(|| {{")
    lines.append("    vec![")

    set_entries = []
    for s in sorted(sets, key=lambda x: x["name"]):
        code = generate_set(s)
        set_entries.append(f"        {code},")

    lines.append("\n".join(set_entries))
    lines.append("    ]")
    lines.append("});")
    lines.append("")  # trailing newline

    return "\n".join(lines)


def main():
    script_dir = Path(__file__).parent
    json_path = script_dir / "sets.json"
    sets_dir = script_dir.parent / "src" / "data" / "sets"

    with open(json_path) as f:
        data = json.load(f)

    # Group sets by type
    by_type: dict[str, list[dict]] = defaultdict(list)
    for s in data["sets"]:
        by_type[s["set_type"]].append(s)

    for set_type, (filename, static_name) in FILE_MAP.items():
        sets = by_type.get(set_type, [])
        content = generate_file(sets, static_name)
        out_path = sets_dir / filename
        out_path.write_text(content)
        print(f"Wrote {out_path} ({len(sets)} sets)")

    total = sum(len(v) for v in by_type.values())
    print(f"\nTotal: {total} sets across {len(FILE_MAP)} files")


if __name__ == "__main__":
    main()
