// Auto-generated by datamine/generate_skills_rs.py - do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::{
    EMPOWER, MAJOR_BERSERK, MAJOR_BREACH, MAJOR_BRUTALITY, MAJOR_PROPHECY, MAJOR_SAVAGERY,
    MAJOR_SORCERY, MINOR_BERSERK, MINOR_VULNERABILITY,
};
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, ClassName, DamageFlags,
    DotDamage, ExecuteScaling, HitDamage, Resource, SkillDamage, SkillData, SkillLineName,
};
use once_cell::sync::Lazy;

pub static NIGHTBLADE_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Ambush",
            "Teleport Strike",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Stamina,
        )
        .with_skill_id(35898)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.071277,
            0.748408,
        )]))
        .with_bonuses(vec![
            MINOR_VULNERABILITY.clone(),
            EMPOWER.clone(),
            MINOR_BERSERK.clone().with_duration(10.0),
        ]),
        SkillData::new(
            "Assassin's Blade",
            "Assassin's Blade",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(35584)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.05,
            0.525,
        )]))
        .with_spammable()
        .with_execute(3.0, 0.25, ExecuteScaling::Flat),
        SkillData::new(
            "Concealed Weapon",
            "Veiled Strike",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(36244)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.11363,
            1.19311,
        )]))
        .with_spammable(),
        SkillData::new(
            "Death Stroke",
            "Death Stroke",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Ultimate,
        )
        .with_skill_id(37518)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.16,
            1.68,
        )]))
        .with_bonuses(vec![BonusData::new(
            "Death Stroke Debuff",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new("Death Stroke Debuff", BonusTarget::EnemyDamageTaken, 0.20),
        )
        .with_duration(8.0)]),
        SkillData::new(
            "Grim Focus",
            "Grim Focus",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(62096)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.18,
            1.89,
        )]))
        .with_proc_light_attacks(4)
        .with_bonuses(vec![
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Impale",
            "Assassin's Blade",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(35596)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.05165,
            0.542325,
        )]))
        .with_spammable()
        .with_execute(3.3, 0.25, ExecuteScaling::Flat),
        SkillData::new(
            "Incapacitating Strike",
            "Death Stroke",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Ultimate,
        )
        .with_skill_id(37532)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::DISEASE | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.16528,
                1.73544,
            ),
            HitDamage::new(
                DamageFlags::DISEASE | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.181808,
                1.90898,
            ),
        ]))
        .with_bonuses(vec![BonusData::new(
            "Incapacitating Strike Debuff",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new(
                "Incapacitating Strike Debuff",
                BonusTarget::EnemyDamageTaken,
                0.20,
            ),
        )
        .with_duration(8.0)]),
        SkillData::new(
            "Killer's Blade",
            "Assassin's Blade",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Stamina,
        )
        .with_skill_id(35590)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::DISEASE | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.05165,
            0.54233,
        )]))
        .with_spammable()
        .with_execute(4.0, 0.5, ExecuteScaling::Linear),
        SkillData::new(
            "Lotus Fan",
            "Teleport Strike",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(35882)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
                    0.071277,
                    0.748408,
                )])
                .with_dots(vec![DotDamage::new(
                    4.0,
                    DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                    0.017683,
                    0.185666,
                )
                .with_interval(1.0)]),
        )
        .with_bonuses(vec![MINOR_VULNERABILITY.clone()]),
        SkillData::new(
            "Mark Target",
            "Mark Target",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(37603)
        .with_bonuses(vec![MAJOR_BREACH.clone()]),
        SkillData::new(
            "Merciless Resolve",
            "Grim Focus",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(62117)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.204534,
            2.14761,
        )]))
        .with_proc_light_attacks(4)
        .with_bonuses(vec![
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Piercing Mark",
            "Mark Target",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(37631)
        .with_bonuses(vec![MAJOR_BREACH.clone().with_duration(60.0)]),
        SkillData::new(
            "Reaper's Mark",
            "Mark Target",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(37658)
        .with_bonuses(vec![
            MAJOR_BREACH.clone(),
            MAJOR_BERSERK.clone().with_duration(10.0),
        ]),
        SkillData::new(
            "Relentless Focus",
            "Grim Focus",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Stamina,
        )
        .with_skill_id(62107)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::DISEASE | DamageFlags::SINGLE_TARGET,
            0.18594,
            1.95237,
        )]))
        .with_proc_light_attacks(4)
        .with_bonuses(vec![
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Soul Harvest",
            "Death Stroke",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Ultimate,
        )
        .with_skill_id(37545)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.16528,
            1.73544,
        )]))
        .with_bonuses(vec![BonusData::new(
            "Soul Harvest Debuff",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new("Soul Harvest Debuff", BonusTarget::EnemyDamageTaken, 0.20),
        )
        .with_duration(8.0)]),
        SkillData::new(
            "Surprise Attack",
            "Veiled Strike",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Stamina,
        )
        .with_skill_id(36234)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.1033,
            1.08465,
        )]))
        .with_spammable()
        .with_bonuses(vec![MAJOR_BREACH.clone()]),
        SkillData::new(
            "Teleport Strike",
            "Teleport Strike",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(35871)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.069,
            0.7245,
        )]))
        .with_bonuses(vec![MINOR_VULNERABILITY.clone()]),
        SkillData::new(
            "Veiled Strike",
            "Veiled Strike",
            ClassName::Nightblade,
            SkillLineName::Assassination,
            Resource::Magicka,
        )
        .with_skill_id(36223)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.1,
            1.05,
        )]))
        .with_spammable(),
        SkillData::new(
            "Aspect of Terror",
            "Aspect of Terror",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(38065),
        SkillData::new(
            "Blur",
            "Blur",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(35909),
        SkillData::new(
            "Bolstering Darkness",
            "Consuming Darkness",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Ultimate,
        )
        .with_skill_id(37744),
        SkillData::new(
            "Consuming Darkness",
            "Consuming Darkness",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Ultimate,
        )
        .with_skill_id(37696),
        SkillData::new(
            "Dark Cloak",
            "Shadow Cloak",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(36351),
        SkillData::new(
            "Dark Shade",
            "Summon Shade",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(36283)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.026858,
            0.28201,
        )])),
        SkillData::new(
            "Manifestation of Terror",
            "Aspect of Terror",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(38096),
        SkillData::new(
            "Mass Hysteria",
            "Aspect of Terror",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(38075),
        SkillData::new(
            "Mirage",
            "Blur",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(35916),
        SkillData::new(
            "Path of Darkness",
            "Path of Darkness",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(37764),
        SkillData::new(
            "Phantasmal Escape",
            "Blur",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(35924),
        SkillData::new(
            "Refreshing Path",
            "Path of Darkness",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(37816),
        SkillData::new(
            "Shadow Cloak",
            "Shadow Cloak",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(36337),
        SkillData::new(
            "Shadow Image",
            "Summon Shade",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(36298)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.02066,
            0.21693,
        )])),
        SkillData::new(
            "Shadowy Disguise",
            "Shadow Cloak",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(36368),
        SkillData::new(
            "Summon Shade",
            "Summon Shade",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(36313)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.02,
            0.21,
        )])),
        SkillData::new(
            "Twisting Path",
            "Path of Darkness",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Magicka,
        )
        .with_skill_id(37796)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.016278,
            0.170915,
        ).with_interval(1.0)])),
        SkillData::new(
            "Veil of Blades",
            "Consuming Darkness",
            ClassName::Nightblade,
            SkillLineName::Shadow,
            Resource::Ultimate,
        )
        .with_skill_id(37713)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            4.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.06198,
            0.65079,
        ).with_interval(1.0)])),
        SkillData::new(
            "Cripple",
            "Cripple",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(37864)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.018182,
            0.19091,
        ).with_interval(2.0)])),
        SkillData::new(
            "Crippling Grasp",
            "Cripple",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(37913)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                    0.05165,
                    0.542325,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                    0.018782,
                    0.19721,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Debilitate",
            "Cripple",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(37887)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.018782,
            0.19721,
        ).with_interval(2.0)])),
        SkillData::new(
            "Drain Power",
            "Drain Power",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(37928)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.075,
            0.7875,
        )]))
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone().with_duration(30.0),
            MAJOR_SORCERY.clone().with_duration(30.0),
        ]),
        SkillData::new(
            "Funnel Health",
            "Strife",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(35941)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.068867,
            0.7231,
        )]))
        .with_spammable(),
        SkillData::new(
            "Healthy Offering",
            "Malevolent Offering",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(36144),
        SkillData::new(
            "Leeching Strikes",
            "Siphoning Strikes",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Stamina,
        )
        .with_skill_id(38015),
        SkillData::new(
            "Malevolent Offering",
            "Malevolent Offering",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(36109),
        SkillData::new(
            "Power Extraction",
            "Drain Power",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Stamina,
        )
        .with_skill_id(37937)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::DISEASE | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        )]))
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone().with_duration(30.0),
            MAJOR_SORCERY.clone().with_duration(30.0),
        ]),
        SkillData::new(
            "Sap Essence",
            "Drain Power",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(37950)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        )]))
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone().with_duration(30.0),
            MAJOR_SORCERY.clone().with_duration(30.0),
        ]),
        SkillData::new(
            "Shrewd Offering",
            "Malevolent Offering",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(36129),
        SkillData::new(
            "Siphoning Attacks",
            "Siphoning Strikes",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Stamina,
        )
        .with_skill_id(38050),
        SkillData::new(
            "Siphoning Strikes",
            "Siphoning Strikes",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Stamina,
        )
        .with_skill_id(37977),
        SkillData::new(
            "Soul Shred",
            "Soul Shred",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Ultimate,
        )
        .with_skill_id(36166)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
                0.15,
                1.575,
            ),
            HitDamage::new(
                DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                0.1388,
                1.4571,
            ),
        ])),
        SkillData::new(
            "Soul Siphon",
            "Soul Shred",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Ultimate,
        )
        .with_skill_id(36186)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.1388,
            1.4571,
        )])),
        SkillData::new(
            "Soul Tether",
            "Soul Shred",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Ultimate,
        )
        .with_skill_id(36207)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![
                    HitDamage::new(
                        DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
                        0.15495,
                        1.62698,
                    ),
                    HitDamage::new(
                        DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                        0.1388,
                        1.4571,
                    ),
                ])
                .with_dots(vec![DotDamage::new(
                    7.0,
                    DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                    0.027,
                    0.2835,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Strife",
            "Strife",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(35931)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.066667,
            0.7,
        )]))
        .with_spammable(),
        SkillData::new(
            "Swallow Soul",
            "Strife",
            ClassName::Nightblade,
            SkillLineName::Siphoning,
            Resource::Magicka,
        )
        .with_skill_id(35949)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.09297,
            0.976185,
        )]))
        .with_spammable(),
    ]
});
