// Auto-generated by datamine/generate_skills_rs.py — do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::unique::{
    MAJOR_BREACH, MINOR_FORCE,
};
use crate::domain::{
    ClassName, DamageFlags, HitDamage, Resource, SkillDamage, SkillData, SkillLineName,
};
use once_cell::sync::Lazy;

pub static PSIJIC_ORDER_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Accelerate",
            "Accelerate",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103503)
        .with_bonuses(vec![MINOR_FORCE.clone()]),
        SkillData::new(
            "Borrowed Time",
            "Borrowed Time",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40104059),
        SkillData::new(
            "Channeled Acceleration",
            "Accelerate",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103706)
        .with_bonuses(vec![MINOR_FORCE.clone().with_duration(60.0)]),
        SkillData::new(
            "Crushing Weapon",
            "Imbue Weapon",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Stamina,
        )
        .with_skill_id(40103623)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.09297,
            0.976185,
        )]))
        .with_spammable()
        .with_bonuses(vec![MAJOR_BREACH.clone().with_duration(5.0)]),
        SkillData::new(
            "Deep Thoughts",
            "Deep Thoughts",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103652),
        SkillData::new(
            "Elemental Weapon",
            "Imbue Weapon",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103571)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.09297,
            0.976185,
        )]))
        .with_spammable(),
        SkillData::new(
            "Imbue Weapon",
            "Imbue Weapon",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Stamina,
        )
        .with_skill_id(40103483)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.09,
            0.945,
        )]))
        .with_spammable(),
        SkillData::new(
            "Introspection",
            "Introspection",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103665),
        SkillData::new(
            "Meditate",
            "Meditate",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103492),
        SkillData::new(
            "Mend Spirit",
            "Mend Spirit",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103747),
        SkillData::new(
            "Mend Wounds",
            "Mend Wounds",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103543),
        SkillData::new(
            "Race Against Time",
            "Accelerate",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103710)
        .with_bonuses(vec![MINOR_FORCE.clone()]),
        SkillData::new(
            "Symbiosis",
            "Symbiosis",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103755),
        SkillData::new(
            "Temporal Guard",
            "Temporal Guard",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Ultimate,
        )
        .with_skill_id(40103564),
        SkillData::new(
            "Time Freeze",
            "Time Freeze",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40104079),
        SkillData::new(
            "Time Stop",
            "Time Stop",
            ClassName::Guild,
            SkillLineName::PsijicOrder,
            Resource::Magicka,
        )
        .with_skill_id(40103488),
    ]
});
