// Auto-generated by datamine/generate_passives_rs.py - do not edit manually.
// Manual overrides (bonuses) stored in generator script.
use crate::domain::{SkillTree, PassiveData, SkillLineName};
use once_cell::sync::Lazy;

pub static PSIJIC_ORDER_PASSIVES: Lazy<Vec<PassiveData>> = Lazy::new(|| {
    vec![
        PassiveData::new(
            "Clairvoyance",
            SkillTree::Guild,
            SkillLineName::PsijicOrder,
            vec![],
        )
        .with_skill_id(103811),
        PassiveData::new(
            "Concentrated Barrier",
            SkillTree::Guild,
            SkillLineName::PsijicOrder,
            vec![],
        )
        .with_skill_id(103964),
        PassiveData::new(
            "Deliberation",
            SkillTree::Guild,
            SkillLineName::PsijicOrder,
            vec![],
        )
        .with_skill_id(103972),
        PassiveData::new(
            "Spell Orb",
            SkillTree::Guild,
            SkillLineName::PsijicOrder,
            vec![],
        )
        .with_skill_id(103878),
    ]
});
