// Auto-generated by datamine/generate_skills_rs.py — do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::{
    MAJOR_BRUTALITY, MAJOR_PROPHECY, MAJOR_SAVAGERY, MAJOR_SORCERY,
};
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, ClassName, DamageFlags, DotDamage, HitDamage, Resource, SkillDamage, SkillData, SkillLineName,
};
use once_cell::sync::Lazy;

pub static ARCANIST_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Arcanist's Domain",
            "Arcanist's Domain",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40183555),
        SkillData::new(
            "Audacious Runemend",
            "Runemend",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40186191),
        SkillData::new(
            "Cascading Fortune",
            "Remedy Cascade",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40186193)
        .with_channel_time(4.5),
        SkillData::new(
            "Chakram Shields",
            "Chakram Shields",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40183447),
        SkillData::new(
            "Chakram of Destiny",
            "Chakram Shields",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40186207),
        SkillData::new(
            "Curative Surge",
            "Remedy Cascade",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40186200)
        .with_channel_time(4.5),
        SkillData::new(
            "Evolving Runemend",
            "Runemend",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40186189),
        SkillData::new(
            "Fleet-Footed Gate",
            "Apocryphal Gate",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40186211),
        SkillData::new(
            "Glyphic of the Tides",
            "Vitalizing Glyphic",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Ultimate,
        )
        .with_skill_id(40193794),
        SkillData::new(
            "Reconstructive Domain",
            "Arcanist's Domain",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40186234),
        SkillData::new(
            "Remedy Cascade",
            "Remedy Cascade",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40183537)
        .with_channel_time(4.5),
        SkillData::new(
            "Resonating Glyphic",
            "Vitalizing Glyphic",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Ultimate,
        )
        .with_skill_id(40193558)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.04132,
            0.43386,
        )])),
        SkillData::new(
            "Runemend",
            "Runemend",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40183261),
        SkillData::new(
            "Tidal Chakram",
            "Chakram Shields",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40186209),
        SkillData::new(
            "Vitalizing Glyphic",
            "Vitalizing Glyphic",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Ultimate,
        )
        .with_skill_id(40183709),
        SkillData::new(
            "Zenas' Empowering Disc",
            "Arcanist's Domain",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            Resource::Magicka,
        )
        .with_skill_id(40186229),
        SkillData::new(
            "Abyssal Impact",
            "Abyssal Impact",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Stamina,
        )
        .with_skill_id(40185817)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.08625,
            0.905625,
        )]))
        .with_spammable()
        .with_bonuses(vec![BonusData::new(
            "Abyssal Ink",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new("Abyssal Ink", BonusTarget::EnemyDamageTaken, 0.05),
        )
        .with_duration(15.0)]),
        SkillData::new(
            "Cephaliarch's Flail",
            "Abyssal Impact",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Stamina,
        )
        .with_skill_id(40183006)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.08625,
            0.905625,
        )]))
        .with_spammable()
        .with_bonuses(vec![BonusData::new(
            "Abyssal Ink",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new("Abyssal Ink", BonusTarget::EnemyDamageTaken, 0.05),
        )
        .with_duration(15.0)]),
        SkillData::new(
            "Escalating Runeblades",
            "Runeblades",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Magicka,
        )
        .with_skill_id(40182977)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![
        HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.03099,
            0.325395,
        ),
        HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.034089,
            0.357932,
        ),
        HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.0408872,
            0.429701,
        ),
        ]))
        .with_spammable(),
        SkillData::new(
            "Exhausting Fatecarver",
            "Fatecarver",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Magicka,
        )
        .with_skill_id(40183122)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.039099,
            0.41054,
        )]))
        .with_channel_time(4.0),
        SkillData::new(
            "Fatecarver",
            "Fatecarver",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Magicka,
        )
        .with_skill_id(40185805)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.03785,
            0.397425,
        )]))
        .with_channel_time(4.0),
        SkillData::new(
            "Fulminating Rune",
            "The Imperfect Ring",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Stamina,
        )
        .with_skill_id(40182988)
        .with_damage(
            SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_aoe(), 0.12912, 1.35581).with_delay(2.0),
        ])),
        SkillData::new(
            "Inspired Scholarship",
            "Tome-Bearer's Inspiration",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Magicka,
        )
        .with_skill_id(40185842)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.040287,
            0.423013,
        )]))
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone(),
            MAJOR_SORCERY.clone(),
        ]),
        SkillData::new(
            "Pragmatic Fatecarver",
            "Fatecarver",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Magicka,
        )
        .with_skill_id(40186366)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.039099,
            0.41054,
        )]))
        .with_channel_time(4.0),
        SkillData::new(
            "Recuperative Treatise",
            "Tome-Bearer's Inspiration",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Magicka,
        )
        .with_skill_id(40183047)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.05165,
            0.54235,
        )]))
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone(),
            MAJOR_SORCERY.clone(),
        ]),
        SkillData::new(
            "Rune of Displacement",
            "The Imperfect Ring",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Stamina,
        )
        .with_skill_id(40185839)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::FROST | DamageFlags::AOE | DamageFlags::MELEE,
            0.12,
            1.26,
        )])
            .with_dots(vec![DotDamage::new(
            18.0,
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.02066,
            0.21693,
        ).with_interval(2.0)])),
        SkillData::new(
            "Runeblades",
            "Runeblades",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Magicka,
        )
        .with_skill_id(40185794)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.03,
            0.315,
        )]))
        .with_spammable(),
        SkillData::new(
            "Tentacular Dread",
            "Abyssal Impact",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Magicka,
        )
        .with_skill_id(40185823)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::FROST | DamageFlags::AOE | DamageFlags::MELEE,
            0.08625,
            0.905625,
        )]))
        .with_spammable()
        .with_bonuses(vec![BonusData::new(
            "Abyssal Ink",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new("Abyssal Ink", BonusTarget::EnemyDamageTaken, 0.05),
        )
        .with_duration(15.0)]),
        SkillData::new(
            "The Imperfect Ring",
            "The Imperfect Ring",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Stamina,
        )
        .with_skill_id(40185836)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::FROST | DamageFlags::AOE | DamageFlags::MELEE,
            0.12,
            1.26,
        )])
            .with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.018182,
            0.19091,
        ).with_interval(2.0)])),
        SkillData::new(
            "The Languid Eye",
            "The Unblinking Eye",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Ultimate,
        )
        .with_skill_id(40189867)
        .with_damage(
            SkillDamage::new().with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::magic_aoe(),
            0.055222,
            0.57983,
        )
        .with_interval(1.0)
        .with_increase_per_tick(0.05)])),
        SkillData::new(
            "The Tide King's Gaze",
            "The Unblinking Eye",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Ultimate,
        )
        .with_skill_id(40189837)
        .with_damage(
            SkillDamage::new()
            .with_dots(vec![DotDamage::new(
            8.0,
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.049584,
            0.520632,
        ).with_interval(0.5)])),
        SkillData::new(
            "The Unblinking Eye",
            "The Unblinking Eye",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Ultimate,
        )
        .with_skill_id(40189791)
        .with_damage(
            SkillDamage::new()
            .with_dots(vec![DotDamage::new(
            6.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.048,
            0.504,
        ).with_interval(0.5)])),
        SkillData::new(
            "Tome-Bearer's Inspiration",
            "Tome-Bearer's Inspiration",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Magicka,
        )
        .with_skill_id(40186452)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.05,
            0.525,
        )]))
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone(),
            MAJOR_SORCERY.clone(),
        ]),
        SkillData::new(
            "Writhing Runeblades",
            "Runeblades",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            Resource::Magicka,
        )
        .with_skill_id(40185803)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.03099,
            0.325395,
        )]))
        .with_spammable(),
        SkillData::new(
            "Cruxweaver Armor",
            "Fatewoven Armor",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40185908)
        .with_bonuses(vec![
            MAJOR_PROPHECY.clone().with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_SAVAGERY.clone().with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Fatewoven Armor",
            "Fatewoven Armor",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40183648)
        .with_bonuses(vec![
            MAJOR_PROPHECY.clone().with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_SAVAGERY.clone().with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Gibbering Shelter",
            "Gibbering Shield",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Ultimate,
        )
        .with_skill_id(40192380),
        SkillData::new(
            "Gibbering Shield",
            "Gibbering Shield",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Ultimate,
        )
        .with_skill_id(40183676),
        SkillData::new(
            "Impervious Runeward",
            "Runespite Ward",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40183241),
        SkillData::new(
            "Rune of Eldritch Horror",
            "Rune of Eldritch Horror",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40185918),
        SkillData::new(
            "Rune of Uncanny Adoration",
            "Rune of Eldritch Horror",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40185921),
        SkillData::new(
            "Rune of the Colorless Pool",
            "Rune of Eldritch Horror",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40183267),
        SkillData::new(
            "Runeguard of Freedom",
            "Runic Defense",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40186489),
        SkillData::new(
            "Runeguard of Still Waters",
            "Runic Defense",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40183401),
        SkillData::new(
            "Runespite Ward",
            "Runespite Ward",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40185894),
        SkillData::new(
            "Runic Defense",
            "Runic Defense",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40185912),
        SkillData::new(
            "Runic Embrace",
            "Runic Jolt",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40186531)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.05165,
            0.542325,
        )]))
        .with_spammable(),
        SkillData::new(
            "Runic Jolt",
            "Runic Jolt",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40183165)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.05,
            0.525,
        )]))
        .with_spammable(),
        SkillData::new(
            "Runic Sunder",
            "Runic Jolt",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Stamina,
        )
        .with_skill_id(40183430)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.05165,
            0.542325,
        )]))
        .with_spammable()
        .with_bonuses(vec![BonusData::new(
            "Runic Sunder Debuff",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new(
                "Runic Sunder Debuff",
                BonusTarget::EnemyResistanceReduction,
                2200.0,
            ),
        )
        .with_duration(15.0)]),
        SkillData::new(
            "Sanctum of the Abyssal Sea",
            "Gibbering Shield",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Ultimate,
        )
        .with_skill_id(40192372),
        SkillData::new(
            "Spiteward of the Lucid Mind",
            "Runespite Ward",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40185901),
        SkillData::new(
            "Unbreakable Fate",
            "Fatewoven Armor",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            Resource::Magicka,
        )
        .with_skill_id(40186477)
        .with_bonuses(vec![
            MAJOR_PROPHECY.clone().with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_SAVAGERY.clone().with_trigger(BonusTrigger::AbilitySlotted),
        ]),
    ]
});
