// Auto-generated by datamine/generate_passives_rs.py - do not edit manually.
// Manual overrides (bonuses) stored in generator script.
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, ClassName, PassiveData,
    SkillLineName,
};
use once_cell::sync::Lazy;

pub static ARCANIST_PASSIVES: Lazy<Vec<PassiveData>> = Lazy::new(|| {
    vec![
        PassiveData::new(
            "Fated Fortune",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            vec![BonusData::new(
                "Fated Fortune",
                BonusSource::Passive,
                BonusTrigger::ArcanistCrux,
                BonusValue::new("Fated Fortune", BonusTarget::CriticalDamage, 0.12),
            )
            .with_duration(7.0)],
        )
        .with_skill_id(184847),
        PassiveData::new(
            "Harnessed Quintessence",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            vec![BonusData::new(
                "Harnessed Quintessence W",
                BonusSource::Passive,
                BonusTrigger::MagickaOrStaminaRestored,
                BonusValue::new(
                    "Harnessed Quintessence W",
                    BonusTarget::WeaponAndSpellDamageFlat,
                    284.0,
                ),
            )
            .with_duration(10.0)],
        )
        .with_skill_id(184858),
        PassiveData::new(
            "Psychic Lesion",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            vec![
                BonusData::new(
                    "Psychic Lesion (Damage)",
                    BonusSource::Passive,
                    BonusTrigger::AbilitySlotted,
                    BonusValue::new(
                        "Psychic Lesion (Damage)",
                        BonusTarget::StatusEffectDamage,
                        0.15,
                    ),
                )
                .with_duration(10.0),
                BonusData::new(
                    "Psychic Lesion (Chance)",
                    BonusSource::Passive,
                    BonusTrigger::AbilitySlotted,
                    BonusValue::new(
                        "Psychic Lesion (Chance)",
                        BonusTarget::StatusEffectChance,
                        0.55,
                    ),
                )
                .with_duration(10.0),
            ],
        )
        .with_skill_id(184873),
        PassiveData::new(
            "Splintered Secrets",
            ClassName::Arcanist,
            SkillLineName::HeraldOfTheTome,
            vec![BonusData::new(
                "Splintered Secrets",
                BonusSource::Passive,
                BonusTrigger::AbilitySlottedCount,
                BonusValue::new(
                    "Splintered Secrets",
                    BonusTarget::PhysicalAndSpellPenetration,
                    1240.0,
                ),
            )
            .with_skill_line_filter(SkillLineName::HeraldOfTheTome)],
        )
        .with_skill_id(184887),
        PassiveData::new(
            "Aegis of the Unseen",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            vec![],
        )
        .with_skill_id(184923),
        PassiveData::new(
            "Circumvented Fate",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            vec![],
        )
        .with_skill_id(184932),
        PassiveData::new(
            "Implacable Outcome",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            vec![],
        )
        .with_skill_id(185058),
        PassiveData::new(
            "Wellspring of the Abyss",
            ClassName::Arcanist,
            SkillLineName::SoldierOfApocrypha,
            vec![],
        )
        .with_skill_id(185036),
        PassiveData::new(
            "Erudition",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            vec![],
        )
        .with_skill_id(185239),
        PassiveData::new(
            "Healing Tides",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            vec![],
        )
        .with_skill_id(185186),
        PassiveData::new(
            "Hideous Clarity",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            vec![BonusData::new(
                "Hideous Clarity",
                BonusSource::Passive,
                BonusTrigger::ArcanistCrux, // TODO: should be only on generate
                BonusValue::new(
                    "Hideous Clarity",
                    BonusTarget::RestoreMagickaOrStamina,
                    225.0,
                ),
            )],
        )
        .with_skill_id(185243),
        PassiveData::new(
            "Intricate Runeforms",
            ClassName::Arcanist,
            SkillLineName::CurativeRuneforms,
            vec![],
        )
        .with_skill_id(185195),
    ]
});
