// Auto-generated by datamine/generate_sets_rs.py — do not edit manually.
// Proc effects are embedded inline from the PROC_EFFECTS dict in the generator.
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, SetData, SetType,
};
use once_cell::sync::Lazy;

pub static ARENA_SETS: Lazy<Vec<SetData>> = Lazy::new(|| {
    vec![
        SetData::new("Archer's Mind", SetType::Arena)
            .with_item_slots(vec!["Medium(All)", "Shield", "Weapons(All)", "Neck", "Ring"])
            .with_threshold(
                2,
                vec![BonusData::new(
                    "Archer's Mind 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
            )
            .with_threshold(
                3,
                vec![BonusData::new(
                    "Archer's Mind 3pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 657.0),
                )],
            )
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Archer's Mind 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 657.0),
                )],
            ),
        SetData::new("Caustic Arrow", SetType::Arena)
            .with_item_slots(vec!["Weapons(Bow)"]),
        SetData::new("Cruel Flurry", SetType::Arena)
            .with_item_slots(vec!["Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Crushing Wall", SetType::Arena)
            .with_item_slots(vec!["Weapons(Lightning Frost Flame)"]),
        SetData::new("Destructive Impact", SetType::Arena)
            .with_item_slots(vec!["Weapons(Lightning Frost Flame)"]),
        SetData::new("Elemental Succession", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(All)", "Light(All)", "Neck", "Ring"])
            .with_threshold(
                2,
                vec![BonusData::new(
                    "Elemental Succession 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
            )
            .with_threshold(
                3,
                vec![BonusData::new(
                    "Elemental Succession 3pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
            )
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Elemental Succession 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
            ),
        SetData::new("Executioner's Blade", SetType::Arena)
            .with_item_slots(vec!["Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Explosive Rebuke", SetType::Arena)
            .with_item_slots(vec!["Heavy(All)", "Shield", "Weapons(All)", "Neck", "Ring"])
            .with_threshold(
                2,
                vec![BonusData::new(
                    "Explosive Rebuke 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
            )
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Explosive Rebuke 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
            ),
        SetData::new("Footman's Fortune", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(All)", "Heavy(All)", "Neck", "Ring"]),
        SetData::new("Force Overflow", SetType::Arena)
            .with_item_slots(vec!["Weapons(Resto)"]),
        SetData::new("Frenzied Momentum", SetType::Arena)
            .with_item_slots(vec!["Weapons(Greatsword Maul Battleaxe)"]),
        SetData::new("Gallant Charge", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Glorious Defender", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(All)", "Heavy(All)", "Neck", "Ring"])
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Glorious Defender 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
            ),
        SetData::new("Grand Rejuvenation", SetType::Arena)
            .with_item_slots(vec!["Weapons(Resto)"]),
        SetData::new("Healer's Habit", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(All)", "Light(All)", "Neck", "Ring"])
            .with_threshold(
                2,
                vec![BonusData::new(
                    "Healer's Habit 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
            )
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Healer's Habit 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
            ),
        SetData::new("Hex Siphon", SetType::Arena)
            .with_item_slots(vec!["Light(All)", "Shield", "Weapons(All)", "Neck", "Ring"])
            .with_threshold(
                2,
                vec![BonusData::new(
                    "Hex Siphon 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
            )
            .with_threshold(
                3,
                vec![BonusData::new(
                    "Hex Siphon 3pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
            )
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Hex Siphon 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 657.0),
                )],
            )
            .with_threshold(
                5,
                vec![BonusData::new(
                    "Hex Siphon 5pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 171.0),
                )],
            ),
        SetData::new("Hunt Leader", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(All)", "Medium(All)", "Neck", "Ring"])
            .with_threshold(
                2,
                vec![BonusData::new(
                    "Hunt Leader 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
            )
            .with_threshold(
                3,
                vec![BonusData::new(
                    "Hunt Leader 3pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
            )
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Hunt Leader 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
            ),
        SetData::new("Mender's Ward", SetType::Arena)
            .with_item_slots(vec!["Weapons(Resto)"]),
        SetData::new("Merciless Charge", SetType::Arena)
            .with_item_slots(vec!["Weapons(Greatsword Maul Battleaxe)"]),
        SetData::new("Para Bellum", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(All)", "Medium(All)", "Neck", "Ring"])
            .with_threshold(
                2,
                vec![BonusData::new(
                    "Para Bellum 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
            )
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Para Bellum 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
            ),
        SetData::new("Perfected Caustic Arrow", SetType::Arena)
            .with_item_slots(vec!["Weapons(Bow)"]),
        SetData::new("Perfected Cruel Flurry", SetType::Arena)
            .with_item_slots(vec!["Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Perfected Crushing Wall", SetType::Arena)
            .with_item_slots(vec!["Weapons(Lightning Frost Flame)"]),
        SetData::new("Perfected Destructive Impact", SetType::Arena)
            .with_item_slots(vec!["Weapons(Lightning Frost Flame)"]),
        SetData::new("Perfected Executioner's Blade", SetType::Arena)
            .with_item_slots(vec!["Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Perfected Force Overflow", SetType::Arena)
            .with_item_slots(vec!["Weapons(Resto)"]),
        SetData::new("Perfected Frenzied Momentum", SetType::Arena)
            .with_item_slots(vec!["Weapons(Greatsword Maul Battleaxe)"]),
        SetData::new("Perfected Gallant Charge", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Perfected Grand Rejuvenation", SetType::Arena)
            .with_item_slots(vec!["Weapons(Resto)"]),
        SetData::new("Perfected Mender's Ward", SetType::Arena)
            .with_item_slots(vec!["Weapons(Resto)"]),
        SetData::new("Perfected Merciless Charge", SetType::Arena)
            .with_item_slots(vec!["Weapons(Greatsword Maul Battleaxe)"]),
        SetData::new("Perfected Point-Blank Snipe", SetType::Arena)
            .with_item_slots(vec!["Weapons(Bow)"]),
        SetData::new("Perfected Precise Regeneration", SetType::Arena)
            .with_item_slots(vec!["Weapons(Resto)"]),
        SetData::new("Perfected Puncturing Remedy", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Perfected Radial Uppercut", SetType::Arena)
            .with_item_slots(vec!["Weapons(Greatsword Maul Battleaxe)"]),
        SetData::new("Perfected Rampaging Slash", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Perfected Spectral Cloak", SetType::Arena)
            .with_item_slots(vec!["Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Perfected Stinging Slashes", SetType::Arena)
            .with_item_slots(vec!["Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Perfected Thunderous Volley", SetType::Arena)
            .with_item_slots(vec!["Weapons(Bow)"]),
        SetData::new("Perfected Titanic Cleave", SetType::Arena)
            .with_item_slots(vec!["Weapons(Greatsword Maul Battleaxe)"]),
        SetData::new("Perfected Virulent Shot", SetType::Arena)
            .with_item_slots(vec!["Weapons(Bow)"]),
        SetData::new("Perfected Void Bash", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Perfected Wild Impulse", SetType::Arena)
            .with_item_slots(vec!["Weapons(Lightning Frost Flame)"]),
        SetData::new("Perfected Wrath of Elements", SetType::Arena)
            .with_item_slots(vec!["Weapons(Lightning Frost Flame)"]),
        SetData::new("Permafrost", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(All)", "Heavy(All)", "Neck", "Ring"])
            .with_threshold(
                3,
                vec![BonusData::new(
                    "Permafrost 3pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
            ),
        SetData::new("Pestilent Host", SetType::Arena)
            .with_item_slots(vec!["Medium(All)", "Shield", "Weapons(All)", "Neck", "Ring"])
            .with_threshold(
                2,
                vec![BonusData::new(
                    "Pestilent Host 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Offensive Penetration", BonusTarget::PhysicalAndSpellPenetration, 1487.0),
                )],
            )
            .with_threshold(
                3,
                vec![BonusData::new(
                    "Pestilent Host 3pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
            )
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Pestilent Host 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
            )
            .with_threshold(
                5,
                vec![BonusData::new(
                    "Pestilent Host 5pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Offensive Penetration", BonusTarget::PhysicalAndSpellPenetration, 1487.0),
                )],
            ),
        SetData::new("Point-Blank Snipe", SetType::Arena)
            .with_item_slots(vec!["Weapons(Bow)"]),
        SetData::new("Precise Regeneration", SetType::Arena)
            .with_item_slots(vec!["Weapons(Resto)"]),
        SetData::new("Puncturing Remedy", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Radial Uppercut", SetType::Arena)
            .with_item_slots(vec!["Weapons(Greatsword Maul Battleaxe)"]),
        SetData::new("Rampaging Slash", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Robes of Destruction Mastery", SetType::Arena)
            .with_item_slots(vec!["Weapons(All)", "Light(All)", "Shield", "Neck", "Ring"])
            .with_threshold(
                2,
                vec![BonusData::new(
                    "Robes of Destruction Mastery 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
            )
            .with_threshold(
                3,
                vec![BonusData::new(
                    "Robes of Destruction Mastery 3pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 657.0),
                )],
            )
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Robes of Destruction Mastery 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
            ),
        SetData::new("Spectral Cloak", SetType::Arena)
            .with_item_slots(vec!["Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Stinging Slashes", SetType::Arena)
            .with_item_slots(vec!["Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Thunderous Volley", SetType::Arena)
            .with_item_slots(vec!["Weapons(Bow)"]),
        SetData::new("Titanic Cleave", SetType::Arena)
            .with_item_slots(vec!["Weapons(Greatsword Maul Battleaxe)"]),
        SetData::new("Virulent Shot", SetType::Arena)
            .with_item_slots(vec!["Weapons(Bow)"]),
        SetData::new("Void Bash", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(Dagger Sword Mace Axe)"]),
        SetData::new("Wild Impulse", SetType::Arena)
            .with_item_slots(vec!["Weapons(Lightning Frost Flame)"]),
        SetData::new("Winterborn", SetType::Arena)
            .with_item_slots(vec!["Shield", "Weapons(All)", "Light(All)", "Neck", "Ring"])
            .with_threshold(
                2,
                vec![BonusData::new(
                    "Winterborn 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
            )
            .with_threshold(
                4,
                vec![BonusData::new(
                    "Winterborn 4pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
            ),
        SetData::new("Wrath of Elements", SetType::Arena)
            .with_item_slots(vec!["Weapons(Lightning Frost Flame)"]),
    ]
});
