// Auto-generated by datamine/generate_sets_rs.py — do not edit manually.
// Proc effects added manually below auto-generated data.
use crate::domain::{{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, DamageFlags, SetData,
    SetProcAction, SetProcEffect, SetProcTrigger, SetType,
}};
use once_cell::sync::Lazy;

pub static MONSTER_SETS: Lazy<Vec<SetData>> = Lazy::new(|| {
    vec![
        SetData::new("Anthelmir's Construct", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Anthelmir's Construct 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
        ),
        SetData::new("Archdruid Devyric", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Archdruid Devyric 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Offensive Penetration", BonusTarget::PhysicalAndSpellPenetration, 1487.0),
                )],
        ),
        SetData::new("Balorgh", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Balorgh 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
        ),
        SetData::new("Baron Thirsk", SetType::Monster),
        SetData::new("Baron Zaudrus", SetType::Monster)
        .with_threshold(
            1,
            vec![
                BonusData::new(
                    "Baron Zaudrus 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 548.0),
                ),
                BonusData::new(
                    "Baron Zaudrus 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 548.0),
                ),
            ],
        ),
        SetData::new("Bloodspawn", SetType::Monster),
        SetData::new("Chokethorn", SetType::Monster),
        SetData::new("Domihaus", SetType::Monster)
        .with_threshold(
            1,
            vec![
                BonusData::new(
                    "Domihaus 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                ),
                BonusData::new(
                    "Domihaus 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                ),
            ],
        ),
        SetData::new("Earthgore", SetType::Monster),
        SetData::new("Encratis's Behemoth", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Encratis's Behemoth 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
        ),
        SetData::new("Engine Guardian", SetType::Monster),
        SetData::new("Euphotic Gatekeeper", SetType::Monster),
        SetData::new("Glorgoloch the Destroyer", SetType::Monster),
        SetData::new("Grothdarr", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Grothdarr 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
        ),
        SetData::new("Grundwulf", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Grundwulf 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 657.0),
                )],
        ),
        SetData::new("Iceheart", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Iceheart 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 657.0),
                )],
        ),
        SetData::new("Ilambris", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Ilambris 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
        ),
        SetData::new("Immolator Charr", SetType::Monster),
        SetData::new("Infernal Guardian", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Infernal Guardian 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
        ),
        SetData::new("Kargaeda", SetType::Monster)
        .with_threshold(
            1,
            vec![
                BonusData::new(
                    "Kargaeda 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 731.0),
                ),
                BonusData::new(
                    "Kargaeda 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 731.0),
                ),
            ],
        ),
        SetData::new("Kjalnar's Nightmare", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Kjalnar's Nightmare 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
        )
        .with_proc_effects(2, vec![SetProcEffect {
            name: "Bone Colossus".to_string(),
            trigger: SetProcTrigger::OnLightAttack,
            action: SetProcAction::DamageProc {
                hit_damage: 8000.0,
                hit_flags: DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::DIRECT,
                dot_total_damage: 0.0,
                dot_duration: 0.0,
                dot_flags: DamageFlags::empty(),
            },
            cooldown: 10.0,
        }]),
        SetData::new("Kra'gh", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Kra'gh 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Offensive Penetration", BonusTarget::PhysicalAndSpellPenetration, 1487.0),
                )],
        ),
        SetData::new("Lady Malygda", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Lady Malygda 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Offensive Penetration", BonusTarget::PhysicalAndSpellPenetration, 1487.0),
                )],
        ),
        SetData::new("Lady Thorn", SetType::Monster),
        SetData::new("Lord Warden", SetType::Monster),
        SetData::new("Maarselok", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Maarselok 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
        ),
        SetData::new("Magma Incarnate", SetType::Monster),
        SetData::new("Maw of the Infernal", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Maw of the Infernal 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
        ),
        SetData::new("Mighty Chudan", SetType::Monster),
        SetData::new("Molag Kena", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Molag Kena 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
        ),
        SetData::new("Mother Ciannait", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Mother Ciannait 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
        ),
        SetData::new("Nazaray", SetType::Monster),
        SetData::new("Nerien'eth", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Nerien'eth 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
        ),
        SetData::new("Nightflame", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Nightflame 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                )],
        ),
        SetData::new("Nunatak", SetType::Monster),
        SetData::new("Ozezan the Inferno", SetType::Monster),
        SetData::new("Pirate Skeleton", SetType::Monster),
        SetData::new("Prior Thierric", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Prior Thierric 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
        ),
        SetData::new("Roksa the Warped", SetType::Monster),
        SetData::new("Scourge Harvester", SetType::Monster),
        SetData::new("Selene", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Selene 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
        ),
        SetData::new("Sellistrix", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Sellistrix 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
        ),
        SetData::new("Sentinel of Rkugamz", SetType::Monster),
        SetData::new("Shadowrend", SetType::Monster),
        SetData::new("Slimecraw", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Slimecraw 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 657.0),
                )],
        )
        .with_threshold(
            2,
            vec![BonusData::new(
                    "Slimecraw 2pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 113.0),
                )],
        ),
        SetData::new("Spawn of Mephala", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Spawn of Mephala 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
        ),
        SetData::new("Stone Husk", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Stone Husk 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 657.0),
                )],
        ),
        SetData::new("Stonekeeper", SetType::Monster)
        .with_threshold(
            1,
            vec![
                BonusData::new(
                    "Stonekeeper 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 548.0),
                ),
                BonusData::new(
                    "Stonekeeper 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 548.0),
                ),
            ],
        ),
        SetData::new("Stormfist", SetType::Monster)
        .with_proc_effects(2, vec![SetProcEffect {
            name: "Stormfist Lightning".to_string(),
            trigger: SetProcTrigger::OnDealDamage,
            action: SetProcAction::DamageProc {
                hit_damage: 2025.0,
                hit_flags: DamageFlags::SHOCK | DamageFlags::AOE | DamageFlags::DIRECT,
                dot_total_damage: 0.0,
                dot_duration: 0.0,
                dot_flags: DamageFlags::empty(),
            },
            cooldown: 8.0,
        }]),
        SetData::new("Swarm Mother", SetType::Monster)
        .with_threshold(
            1,
            vec![
                BonusData::new(
                    "Swarm Mother 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                ),
                BonusData::new(
                    "Swarm Mother 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Magicka", BonusTarget::MaxMagickaFlat, 1096.0),
                ),
            ],
        ),
        SetData::new("Symphony of Blades", SetType::Monster),
        SetData::new("The Blind", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "The Blind 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 657.0),
                )],
        ),
        SetData::new("The Troll King", SetType::Monster),
        SetData::new("Thurvokun", SetType::Monster),
        SetData::new("Tremorscale", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Tremorscale 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
        ),
        SetData::new("Valkyn Skoria", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Valkyn Skoria 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Offensive Penetration", BonusTarget::PhysicalAndSpellPenetration, 1487.0),
                )],
        ),
        SetData::new("Velidreth", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Velidreth 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Weapon and Spell Damage", BonusTarget::WeaponAndSpellDamageFlat, 129.0),
                )],
        ),
        SetData::new("Vykosa", SetType::Monster),
        SetData::new("Zaan", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Zaan 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Critical Chance", BonusTarget::CriticalRating, 657.0),
                )],
        )
        .with_proc_effects(2, vec![SetProcEffect {
            name: "Zaan Fire Beam".to_string(),
            trigger: SetProcTrigger::OnDealDamage,
            action: SetProcAction::DamageProc {
                hit_damage: 0.0,
                hit_flags: DamageFlags::empty(),
                dot_total_damage: 9000.0,
                dot_duration: 6.0,
                dot_flags: DamageFlags::FLAME | DamageFlags::SINGLE_TARGET | DamageFlags::DOT,
            },
            cooldown: 18.0,
        }]),
        SetData::new("Zoal the Ever-Wakeful", SetType::Monster)
        .with_threshold(
            1,
            vec![BonusData::new(
                    "Zoal the Ever-Wakeful 1pc",
                    BonusSource::GearSet,
                    BonusTrigger::Passive,
                    BonusValue::new("Max Stamina", BonusTarget::MaxStaminaFlat, 1096.0),
                )],
        ),
    ]
});
