// Auto-generated by datamine/generate_sets_rs.py — do not edit manually.
use crate::domain::{{SetData, SetType}};
use once_cell::sync::Lazy;

pub static MYTHIC_SETS: Lazy<Vec<SetData>> = Lazy::new(|| {
    vec![
        SetData::new("Belharza's Band", SetType::Mythic),
        SetData::new("Bloodlord's Embrace", SetType::Mythic),
        SetData::new("Cryptcanon Vestments", SetType::Mythic),
        SetData::new("Death Dealer's Fete", SetType::Mythic),
        SetData::new("Dov-rha Sabatons", SetType::Mythic),
        SetData::new("Esoteric Environment Greaves", SetType::Mythic),
        SetData::new("Faun's Lark Cladding", SetType::Mythic),
        SetData::new("Gaze of Sithis", SetType::Mythic),
        SetData::new("Harpooner's Wading Kilt", SetType::Mythic),
        SetData::new("Lefthander's Aegis Belt", SetType::Mythic),
        SetData::new("Malacath's Band of Brutality", SetType::Mythic),
        SetData::new("Markyn Ring of Majesty", SetType::Mythic),
        SetData::new("Mora's Whispers", SetType::Mythic),
        SetData::new("Oakensoul Ring", SetType::Mythic),
        SetData::new("Pearls of Ehlnofey", SetType::Mythic),
        SetData::new("Ring of the Pale Order", SetType::Mythic),
        SetData::new("Ring of the Wild Hunt", SetType::Mythic),
        SetData::new("Rourken Steamguards", SetType::Mythic),
        SetData::new("Sea-Serpent's Coil", SetType::Mythic),
        SetData::new("Shapeshifter's Chain", SetType::Mythic),
        SetData::new("Snow Treaders", SetType::Mythic),
        SetData::new("Spaulder of Ruin", SetType::Mythic),
        SetData::new("Stormweaver's Cavort", SetType::Mythic),
        SetData::new("Syrabane's Ward", SetType::Mythic),
        SetData::new("The Saint and the Seducer", SetType::Mythic),
        SetData::new("The Shadow Queen's Cowl", SetType::Mythic),
        SetData::new("Thrassian Stranglers", SetType::Mythic),
        SetData::new("Torc of Tonal Constancy", SetType::Mythic),
        SetData::new("Torc of the Last Ayleid King", SetType::Mythic),
        SetData::new("Velothi Ur-Mage's Amulet", SetType::Mythic),
    ]
});
