// Auto-generated by datamine/generate_sets_rs.py - do not edit manually.
// Proc effects are embedded inline from the PROC_EFFECTS dict in the generator.
use crate::domain::{DamageFlags, SetData, SetProcAction, SetProcEffect, SetProcTrigger, SetType};
use once_cell::sync::Lazy;

pub static MYTHIC_SETS: Lazy<Vec<SetData>> = Lazy::new(|| {
    vec![
        SetData::new("Belharza's Band", SetType::Mythic)
            .with_item_slots(vec!["Ring"])
            .with_proc_effects(
                1,
                vec![
                    SetProcEffect {
                        name: "Belharza's Band LA Bonus".to_string(),
                        trigger: SetProcTrigger::OnLightAttack,
                        action: SetProcAction::FlatLightAttackBonus { value: 900.0 },
                        cooldown: 0.0,
                    },
                    SetProcEffect {
                        name: "Belharza's Band Proc".to_string(),
                        trigger: SetProcTrigger::OnLightAttack,
                        action: SetProcAction::DamageProc {
                            hit_damage: 1471.0,
                            hit_flags: DamageFlags::PHYSICAL
                                | DamageFlags::SINGLE_TARGET
                                | DamageFlags::DIRECT,
                            dot_total_damage: 0.0,
                            dot_duration: 0.0,
                            dot_flags: DamageFlags::empty(),
                        },
                        cooldown: 10.0,
                    },
                ],
            ),
        SetData::new("Bloodlord's Embrace", SetType::Mythic).with_item_slots(vec!["Heavy(Chest)"]),
        SetData::new("Cryptcanon Vestments", SetType::Mythic).with_item_slots(vec!["Light(Chest)"]),
        SetData::new("Death Dealer's Fete", SetType::Mythic).with_item_slots(vec!["Ring"]),
        SetData::new("Dov-rha Sabatons", SetType::Mythic).with_item_slots(vec!["Heavy(Feet)"]),
        SetData::new("Esoteric Environment Greaves", SetType::Mythic)
            .with_item_slots(vec!["Heavy(Leg)"]),
        SetData::new("Faun's Lark Cladding", SetType::Mythic)
            .with_item_slots(vec!["Medium(Chest)"]),
        SetData::new("Gaze of Sithis", SetType::Mythic).with_item_slots(vec!["Heavy(Head)"]),
        SetData::new("Harpooner's Wading Kilt", SetType::Mythic)
            .with_item_slots(vec!["Medium(Leg)"]),
        SetData::new("Lefthander's Aegis Belt", SetType::Mythic)
            .with_item_slots(vec!["Medium(Waist)"]),
        SetData::new("Malacath's Band of Brutality", SetType::Mythic).with_item_slots(vec!["Ring"]),
        SetData::new("Markyn Ring of Majesty", SetType::Mythic).with_item_slots(vec!["Ring"]),
        SetData::new("Mora's Whispers", SetType::Mythic).with_item_slots(vec!["Light(Shoulder)"]),
        SetData::new("Oakensoul Ring", SetType::Mythic).with_item_slots(vec!["Ring"]),
        SetData::new("Pearls of Ehlnofey", SetType::Mythic).with_item_slots(vec!["Neck"]),
        SetData::new("Ring of the Pale Order", SetType::Mythic).with_item_slots(vec!["Ring"]),
        SetData::new("Ring of the Wild Hunt", SetType::Mythic).with_item_slots(vec!["Ring"]),
        SetData::new("Rourken Steamguards", SetType::Mythic).with_item_slots(vec!["Heavy(Hand)"]),
        SetData::new("Sea-Serpent's Coil", SetType::Mythic).with_item_slots(vec!["Neck"]),
        SetData::new("Shapeshifter's Chain", SetType::Mythic).with_item_slots(vec!["Neck"]),
        SetData::new("Snow Treaders", SetType::Mythic).with_item_slots(vec!["Medium(Feet)"]),
        SetData::new("Spaulder of Ruin", SetType::Mythic).with_item_slots(vec!["Light(Shoulder)"]),
        SetData::new("Stormweaver's Cavort", SetType::Mythic).with_item_slots(vec!["Light(Leg)"]),
        SetData::new("Syrabane's Ward", SetType::Mythic).with_item_slots(vec!["Heavy(Waist)"]),
        SetData::new("The Saint and the Seducer", SetType::Mythic).with_item_slots(vec!["Neck"]),
        SetData::new("The Shadow Queen's Cowl", SetType::Mythic)
            .with_item_slots(vec!["Light(Head)"]),
        SetData::new("Thrassian Stranglers", SetType::Mythic).with_item_slots(vec!["Light(Hand)"]),
        SetData::new("Torc of Tonal Constancy", SetType::Mythic).with_item_slots(vec!["Neck"]),
        SetData::new("Torc of the Last Ayleid King", SetType::Mythic).with_item_slots(vec!["Neck"]),
        SetData::new("Velothi Ur-Mage's Amulet", SetType::Mythic).with_item_slots(vec!["Neck"]),
    ]
});
