// Auto-generated by datamine/generate_sets_rs.py — do not edit manually.
// Proc effects added manually below auto-generated data.
use crate::domain::{
    DamageFlags, SetData, SetProcAction, SetProcEffect, SetProcTrigger, SetType,
};
use once_cell::sync::Lazy;

pub static MYTHIC_SETS: Lazy<Vec<SetData>> = Lazy::new(|| {
    vec![
        SetData::new("Belharza's Band", SetType::Mythic)
        .with_proc_effects(1, vec![
            SetProcEffect {
                name: "Belharza's Band LA Bonus".to_string(),
                trigger: SetProcTrigger::OnLightAttack,
                action: SetProcAction::FlatLightAttackBonus { value: 900.0 },
                cooldown: 0.0,
            },
            SetProcEffect {
                name: "Belharza's Band Proc".to_string(),
                trigger: SetProcTrigger::OnLightAttack,
                action: SetProcAction::DamageProc {
                    hit_damage: 1471.0,
                    hit_flags: DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::DIRECT,
                    dot_total_damage: 0.0,
                    dot_duration: 0.0,
                    dot_flags: DamageFlags::empty(),
                },
                cooldown: 10.0,
            },
        ]),
        SetData::new("Bloodlord's Embrace", SetType::Mythic),
        SetData::new("Cryptcanon Vestments", SetType::Mythic),
        SetData::new("Death Dealer's Fete", SetType::Mythic),
        SetData::new("Dov-rha Sabatons", SetType::Mythic),
        SetData::new("Esoteric Environment Greaves", SetType::Mythic),
        SetData::new("Faun's Lark Cladding", SetType::Mythic),
        SetData::new("Gaze of Sithis", SetType::Mythic),
        SetData::new("Harpooner's Wading Kilt", SetType::Mythic),
        SetData::new("Lefthander's Aegis Belt", SetType::Mythic),
        SetData::new("Malacath's Band of Brutality", SetType::Mythic),
        SetData::new("Markyn Ring of Majesty", SetType::Mythic),
        SetData::new("Mora's Whispers", SetType::Mythic),
        SetData::new("Oakensoul Ring", SetType::Mythic),
        SetData::new("Pearls of Ehlnofey", SetType::Mythic),
        SetData::new("Ring of the Pale Order", SetType::Mythic),
        SetData::new("Ring of the Wild Hunt", SetType::Mythic),
        SetData::new("Rourken Steamguards", SetType::Mythic),
        SetData::new("Sea-Serpent's Coil", SetType::Mythic),
        SetData::new("Shapeshifter's Chain", SetType::Mythic),
        SetData::new("Snow Treaders", SetType::Mythic),
        SetData::new("Spaulder of Ruin", SetType::Mythic),
        SetData::new("Stormweaver's Cavort", SetType::Mythic),
        SetData::new("Syrabane's Ward", SetType::Mythic),
        SetData::new("The Saint and the Seducer", SetType::Mythic),
        SetData::new("The Shadow Queen's Cowl", SetType::Mythic),
        SetData::new("Thrassian Stranglers", SetType::Mythic),
        SetData::new("Torc of Tonal Constancy", SetType::Mythic),
        SetData::new("Torc of the Last Ayleid King", SetType::Mythic),
        SetData::new("Velothi Ur-Mage's Amulet", SetType::Mythic),
    ]
});
