// Auto-generated by datamine/generate_passives_rs.py — do not edit manually.
// Manual overrides (bonuses) stored in generator script.
use crate::data::bonuses::MINOR_BRUTALITY;
use crate::domain::{BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, ClassName, PassiveData, SkillLineName};
use once_cell::sync::Lazy;

pub static DRAGONKNIGHT_PASSIVES: Lazy<Vec<PassiveData>> = Lazy::new(|| {
    vec![
        PassiveData::new(
            "Combustion",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            vec![
                BonusData::new(
                    "Combustion (Damage)",
                    BonusSource::Passive,
                    BonusTrigger::Passive,
                    BonusValue::new(
                        "Combustion (Damage)",
                        BonusTarget::BurningAndPoisonDamage,
                        0.33,
                    ),
                ),
                BonusData::new(
                    "Combustion (Restore)",
                    BonusSource::Passive,
                    BonusTrigger::BurningOrPoisonDamageDealt,
                    BonusValue::new(
                        "Combustion (Restore)",
                        BonusTarget::RestoreMagickaOrStamina,
                        423.0,
                    ),
                )
                .with_cooldown(3.0),
            ],
        )
            .with_skill_id(45011),
        PassiveData::new(
            "Searing Heat",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            vec![], // TODO: Passive effect to specific skills.,
        )
            .with_skill_id(45023),
        PassiveData::new(
            "Warmth",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            vec![BonusData::new(
                "Warmth",
                BonusSource::Passive,
                BonusTrigger::SkillLineSkillCast,
                BonusValue::new("Warmth", BonusTarget::AoeDamage, 0.06),
            )
            .with_duration(3.0)],
        )
            .with_skill_id(45012),
        PassiveData::new(
            "World in Ruin",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            vec![BonusData::new(
                "World in Ruin",
                BonusSource::Passive,
                BonusTrigger::Passive,
                BonusValue::new("World in Ruin", BonusTarget::BurningAndPoisonDamage, 0.05),
            )],
        )
            .with_skill_id(45029),
        PassiveData::new(
            "Burning Heart",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            vec![],
        )
            .with_skill_id(44933),
        PassiveData::new(
            "Elder Dragon",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            vec![],
        )
            .with_skill_id(44951),
        PassiveData::new(
            "Iron Skin",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            vec![],
        )
            .with_skill_id(44922),
        PassiveData::new(
            "Scaled Armor",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            vec![],
        )
            .with_skill_id(44953),
        PassiveData::new(
            "Battle Roar",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            vec![], // TODO: To complex, restore resources on ult cast,
        )
            .with_skill_id(44984),
        PassiveData::new(
            "Eternal Mountain",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            vec![BonusData::new(
                "Eternal Mountain",
                BonusSource::Passive,
                BonusTrigger::Passive,
                BonusValue::new(
                    "Eternal Mountain",
                    BonusTarget::DurationSkillLineMultiplier,
                    0.2,
                ),
            )],
        )
            .with_skill_id(44996),
        PassiveData::new(
            "Helping Hands",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            vec![], // TODO: To complex, restore stamina on skill use with multiple conditions,
        )
            .with_skill_id(45009),
        PassiveData::new(
            "Mountain's Blessing",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            vec![
                MINOR_BRUTALITY
                    .clone()
                    .with_trigger(BonusTrigger::SkillLineSkillCast)
                    .with_cooldown(6.0),
                // TODO: Generates 3 ultimate
            ],
        )
            .with_skill_id(45001),
    ]
});
