// Auto-generated by datamine/generate_skills_rs.py — do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::{EMPOWER, MAJOR_BREACH, MAJOR_BRUTALITY, MAJOR_SORCERY};
use crate::domain::{
    ClassName, DamageFlags, DotDamage, HitDamage, Resource, SkillDamage, SkillData, SkillLineName,
};
use once_cell::sync::Lazy;

pub static DRAGONKNIGHT_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Burning Embers",
            "Searing Strike",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(23898)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                    0.05165,
                    0.542325,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
                    0.015495,
                    0.162697,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Cauterize",
            "Inferno",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(34100)
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone().with_duration(20.0),
            MAJOR_SORCERY.clone().with_duration(20.0),
        ]),
        SkillData::new(
            "Chains of Devastation",
            "Fiery Grip",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(32229)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.06198,
            0.65079,
        )])),
        SkillData::new(
            "Dragonknight Standard",
            "Dragonknight Standard",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Ultimate,
        )
        .with_skill_id(33963)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                    0.15,
                    1.575,
                )])
                .with_dots(vec![DotDamage::new(
                    16.0,
                    DamageFlags::FLAME | DamageFlags::AOE,
                    0.0375,
                    0.39375,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Engulfing Flames",
            "Fiery Breath",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(34048)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                    0.077475,
                    0.813488,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
                    0.012913,
                    0.135581,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Fiery Breath",
            "Fiery Breath",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(34031)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                    0.075,
                    0.7875,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
                    0.0125,
                    0.13125,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Fiery Grip",
            "Fiery Grip",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(23744)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.06,
            0.63,
        )])),
        SkillData::new(
            "Flame Lash",
            "Lava Whip",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(23924)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::FLAME | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.1033,
                1.08465,
            ),
            HitDamage::new(
                DamageFlags::FLAME | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.118795,
                1.24735,
            ),
        ]))
        .with_spammable(),
        SkillData::new(
            "Flames of Oblivion",
            "Inferno",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(34080)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.077475,
            0.813488,
        )]))
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone().with_duration(20.0),
            MAJOR_SORCERY.clone().with_duration(20.0),
        ]),
        SkillData::new(
            "Inferno",
            "Inferno",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(34061)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.075,
            0.7875,
        )]))
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone().with_duration(20.0),
            MAJOR_SORCERY.clone().with_duration(20.0),
        ]),
        SkillData::new(
            "Lava Whip",
            "Lava Whip",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(23811)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.1,
            1.05,
        )]))
        .with_spammable(),
        SkillData::new(
            "Molten Whip",
            "Lava Whip",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(23819)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.1033,
            1.08465,
        )]))
        .with_spammable(),
        SkillData::new(
            "Noxious Breath",
            "Fiery Breath",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Stamina,
        )
        .with_skill_id(34039)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::POISON | DamageFlags::AOE | DamageFlags::MELEE,
                    0.077475,
                    0.813488,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::POISON | DamageFlags::SINGLE_TARGET,
                    0.012913,
                    0.135581,
                )
                .with_interval(2.0)]),
        )
        .with_bonuses(vec![MAJOR_BREACH.clone()]),
        SkillData::new(
            "Searing Strike",
            "Searing Strike",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(23886)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                    0.05,
                    0.525,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
                    0.015,
                    0.1575,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Shifting Standard",
            "Dragonknight Standard",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Ultimate,
        )
        .with_skill_id(33987)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                    0.15,
                    1.575,
                )])
                .with_dots(vec![DotDamage::new(
                    25.0,
                    DamageFlags::FLAME | DamageFlags::AOE,
                    0.038737,
                    0.406744,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Standard of Might",
            "Dragonknight Standard",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Ultimate,
        )
        .with_skill_id(34021)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                    0.15,
                    1.575,
                )])
                .with_dots(vec![DotDamage::new(
                    16.0,
                    DamageFlags::FLAME | DamageFlags::AOE,
                    0.038737,
                    0.406744,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Unrelenting Grip",
            "Fiery Grip",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Magicka,
        )
        .with_skill_id(23778)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.06198,
            0.65079,
        )])),
        SkillData::new(
            "Venomous Claw",
            "Searing Strike",
            ClassName::Dragonknight,
            SkillLineName::ArdentFlame,
            Resource::Stamina,
        )
        .with_skill_id(23915)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::poison_single(),
                    0.05165,
                    0.542325,
                )])
                .with_dots(vec![DotDamage::new(
                    20.0,
                    DamageFlags::poison_single(),
                    0.015495,
                    0.162697,
                )
                .with_interval(2.0)
                .with_increase_per_tick(0.12)]),
        ),
        SkillData::new(
            "Burning Talons",
            "Dark Talons",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(32123)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![
                    HitDamage::new(
                        DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                        0.077475,
                        0.813488,
                    ),
                    HitDamage::new(
                        DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                        0.125,
                        1.3125,
                    ),
                ])
                .with_dots(vec![DotDamage::new(
                    4.0,
                    DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
                    0.014118,
                    0.148235,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Choking Talons",
            "Dark Talons",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(32135)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                0.077475,
                0.813488,
            ),
            HitDamage::new(
                DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                0.125,
                1.3125,
            ),
        ])),
        SkillData::new(
            "Coagulating Blood",
            "Dragon Blood",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(33646),
        SkillData::new(
            "Dark Talons",
            "Dark Talons",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(32111)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                0.075,
                0.7875,
            ),
            HitDamage::new(
                DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                0.125,
                1.3125,
            ),
        ])),
        SkillData::new(
            "Deep Breath",
            "Inhale",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(33715)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_aoe(), 0.077475, 0.813488).with_delay(2.5),
        ]))
        .with_channel_time(2.5),
        SkillData::new(
            "Dragon Blood",
            "Dragon Blood",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(33619),
        SkillData::new(
            "Dragon Fire Scale",
            "Protective Scale",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(33759)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.077475,
            0.813488,
        )])),
        SkillData::new(
            "Dragon Leap",
            "Dragon Leap",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Ultimate,
        )
        .with_skill_id(33658)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.1825,
            1.91625,
        )])),
        SkillData::new(
            "Draw Essence",
            "Inhale",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(33732)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_aoe(), 0.077475, 0.813488).with_delay(2.5),
        ]))
        .with_channel_time(2.5),
        SkillData::new(
            "Ferocious Leap",
            "Dragon Leap",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Ultimate,
        )
        .with_skill_id(33679)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
            0.188523,
            1.97949,
        )])),
        SkillData::new(
            "Green Dragon Blood",
            "Dragon Blood",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(33632),
        SkillData::new(
            "Hardened Armor",
            "Spiked Armor",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(23856),
        SkillData::new(
            "Inhale",
            "Inhale",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(33697)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_aoe(), 0.075, 0.7875).with_delay(2.5),
        ]))
        .with_channel_time(2.5),
        SkillData::new(
            "Protective Plate",
            "Protective Scale",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(33749),
        SkillData::new(
            "Protective Scale",
            "Protective Scale",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(33743),
        SkillData::new(
            "Spiked Armor",
            "Spiked Armor",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(23828),
        SkillData::new(
            "Take Flight",
            "Dragon Leap",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Ultimate,
        )
        .with_skill_id(33668)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.216801,
            2.27641,
        )])),
        SkillData::new(
            "Volatile Armor",
            "Spiked Armor",
            ClassName::Dragonknight,
            SkillLineName::DraconicPower,
            Resource::Magicka,
        )
        .with_skill_id(23842),
        SkillData::new(
            "Ash Cloud",
            "Ash Cloud",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(33778),
        SkillData::new(
            "Cinder Storm",
            "Ash Cloud",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(33797),
        SkillData::new(
            "Corrosive Armor",
            "Magma Armor",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Ultimate,
        )
        .with_skill_id(33852)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::POISON | DamageFlags::AOE,
            0.015,
            0.1575,
        ).with_interval(1.0)])),
        SkillData::new(
            "Eruption",
            "Ash Cloud",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(33816)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                    0.077475,
                    0.813488,
                )])
                .with_dots(vec![DotDamage::new(
                    15.0,
                    DamageFlags::FLAME | DamageFlags::AOE,
                    0.013773,
                    0.14462,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Fossilize",
            "Petrify",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(33921)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_single(), 0.06198, 0.65079).with_delay(3.5),
        ])),
        SkillData::new(
            "Fragmented Shield",
            "Obsidian Shield",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(33881),
        SkillData::new(
            "Igneous Shield",
            "Obsidian Shield",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(33872),
        SkillData::new(
            "Igneous Weapons",
            "Molten Weapons",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(32166)
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
        SkillData::new(
            "Magma Armor",
            "Magma Armor",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Ultimate,
        )
        .with_skill_id(19982)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::FLAME | DamageFlags::AOE,
            0.015,
            0.1575,
        ).with_interval(1.0)])),
        SkillData::new(
            "Magma Shell",
            "Magma Armor",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Ultimate,
        )
        .with_skill_id(33841)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::FLAME | DamageFlags::AOE,
            0.015,
            0.1575,
        ).with_interval(1.0)])),
        SkillData::new(
            "Molten Armaments",
            "Molten Weapons",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(32173)
        .with_bonuses(vec![
            EMPOWER.clone(),
            MAJOR_BRUTALITY.clone(),
            MAJOR_SORCERY.clone(),
        ]),
        SkillData::new(
            "Molten Weapons",
            "Molten Weapons",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(32156)
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
        SkillData::new(
            "Obsidian Shard",
            "Stonefist",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(32199)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.02,
            0.21,
        )]))
        .with_spammable(),
        SkillData::new(
            "Obsidian Shield",
            "Obsidian Shield",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(33866),
        SkillData::new(
            "Petrify",
            "Petrify",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(33898)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_single(), 0.06, 0.63).with_delay(3.0),
        ])),
        SkillData::new(
            "Shattering Rocks",
            "Petrify",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Magicka,
        )
        .with_skill_id(33944)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_single(), 0.06198, 0.65079).with_delay(3.0),
        ])),
        SkillData::new(
            "Stone Giant",
            "Stonefist",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Stamina,
        )
        .with_skill_id(32205)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
                0.1033,
                1.08465,
            ),
            HitDamage::new(
                DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
                0.1033,
                1.08465,
            ),
        ]))
        .with_spammable(),
        SkillData::new(
            "Stonefist",
            "Stonefist",
            ClassName::Dragonknight,
            SkillLineName::EarthenHeart,
            Resource::Stamina,
        )
        .with_skill_id(32194)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
                0.1,
                1.05,
            ),
            HitDamage::new(
                DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
                0.1,
                1.05,
            ),
        ]))
        .with_spammable(),
    ]
});
