// Auto-generated by datamine/generate_skills_rs.py — do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::unique::{
    MINOR_VULNERABILITY,
};
use crate::domain::{
    ClassName, DamageFlags, DotDamage, HitDamage, Resource, SkillDamage, SkillData, SkillLineName,
};
use once_cell::sync::Lazy;

pub static UNDAUNTED_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Blood Altar",
            "Blood Altar",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Stamina,
        )
        .with_skill_id(43251),
        SkillData::new(
            "Bone Shield",
            "Bone Shield",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Stamina,
        )
        .with_skill_id(43310),
        SkillData::new(
            "Bone Surge",
            "Bone Surge",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Stamina,
        )
        .with_skill_id(43334),
        SkillData::new(
            "Energy Orb",
            "Energy Orb",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Magicka,
        )
        .with_skill_id(43447),
        SkillData::new(
            "Inner Beast",
            "Inner Fire",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Stamina,
        )
        .with_skill_id(43393)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![
        HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.09297,
            0.976185,
        ),
        HitDamage::new(
            DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
            0.1,
            1.05,
        ),
        ])
            .with_dots(vec![DotDamage::new(
            2.0,
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.02,
            0.21,
        ).with_interval(1.0)]))
        .with_bonuses(vec![MINOR_VULNERABILITY.clone().with_duration(15.0)]),
        SkillData::new(
            "Inner Fire",
            "Inner Fire",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Magicka,
        )
        .with_skill_id(43363)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![
        HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.045,
            0.4725,
        ),
        HitDamage::new(
            DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
            0.1,
            1.05,
        ),
        ])
            .with_dots(vec![DotDamage::new(
            2.0,
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.02,
            0.21,
        ).with_interval(1.0)])),
        SkillData::new(
            "Inner Rage",
            "Inner Fire",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Magicka,
        )
        .with_skill_id(43378)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![
        HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.046485,
            0.488093,
        ),
        HitDamage::new(
            DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
            0.1,
            1.05,
        ),
        ])
            .with_dots(vec![DotDamage::new(
            2.0,
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.02,
            0.21,
        ).with_interval(1.0)])),
        SkillData::new(
            "Mystic Orb",
            "Necrotic Orb",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Magicka,
        )
        .with_skill_id(43415)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.1,
            1.05,
        )])
            .with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.014086,
            0.147907,
        ).with_interval(1.0)])),
        SkillData::new(
            "Necrotic Orb",
            "Necrotic Orb",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Magicka,
        )
        .with_skill_id(43406)
        .with_damage(
            SkillDamage::new()
            .with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.1,
            1.05,
        )])
            .with_dots(vec![DotDamage::new(
            10.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.013636,
            0.143182,
        ).with_interval(1.0)])),
        SkillData::new(
            "Overflowing Altar",
            "Overflowing Altar",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Stamina,
        )
        .with_skill_id(43287),
        SkillData::new(
            "Sanguine Altar",
            "Sanguine Altar",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Stamina,
        )
        .with_skill_id(43266),
        SkillData::new(
            "Shadow Silk",
            "Trapping Webs",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Stamina,
        )
        .with_skill_id(43489)
        .with_damage(
            SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::physical_aoe(), 0.077475, 0.813488),
            HitDamage::new(DamageFlags::poison_aoe(), 0.1033, 1.08465).with_delay(10.0),
        ])),
        SkillData::new(
            "Spiked Bone Shield",
            "Spiked Bone Shield",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Stamina,
        )
        .with_skill_id(43323),
        SkillData::new(
            "Tangling Webs",
            "Trapping Webs",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Stamina,
        )
        .with_skill_id(43477)
        .with_damage(
            SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::physical_aoe(), 0.077475, 0.813488),
            HitDamage::new(DamageFlags::poison_aoe(), 0.1033, 1.08465).with_delay(10.0),
        ])),
        SkillData::new(
            "Trapping Webs",
            "Trapping Webs",
            ClassName::Guild,
            SkillLineName::Undaunted,
            Resource::Stamina,
        )
        .with_skill_id(43541)
        .with_damage(
            SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::physical_aoe(), 0.075, 0.7875),
            HitDamage::new(DamageFlags::poison_aoe(), 0.1, 1.05).with_delay(10.0),
        ])),
    ]
});
