// Auto-generated by datamine/generate_passives_rs.py - do not edit manually.
// Manual overrides (bonuses) stored in generator script.
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, SkillTree, PassiveData,
    SkillLineName,
};
use once_cell::sync::Lazy;

pub static BOW_PASSIVES: Lazy<Vec<PassiveData>> = Lazy::new(|| {
    vec![
        PassiveData::new(
            "Accuracy",
            SkillTree::Weapon,
            SkillLineName::Bow,
            vec![BonusData::new(
                "Accuracy",
                BonusSource::Passive,
                BonusTrigger::BowEquipped,
                BonusValue::new("Accuracy", BonusTarget::CriticalRating, 1314.0),
            )],
        )
        .with_skill_id(45492),
        PassiveData::new(
            "Hasty Retreat",
            SkillTree::Weapon,
            SkillLineName::Bow,
            vec![],
        )
        .with_skill_id(45498),
        PassiveData::new(
            "Hawk Eye",
            SkillTree::Weapon,
            SkillLineName::Bow,
            vec![], // TODO: To complex, Stacks per basic of increase damage,
        )
        .with_skill_id(45497),
        PassiveData::new(
            "Long Shots",
            SkillTree::Weapon,
            SkillLineName::Bow,
            vec![BonusData::new(
                "Long Shots",
                BonusSource::Passive,
                BonusTrigger::BowEquipped,
                BonusValue::new("Long Shots (Damage)", BonusTarget::Damage, 0.05),
            )
            .with_alternative(BonusValue::new(
                "Long Shots (Crit Rating)",
                BonusTarget::CriticalRating,
                1314.0,
            ))],
        ),
        PassiveData::new("Ranger", SkillTree::Weapon, SkillLineName::Bow, vec![])
            .with_skill_id(45493),
        PassiveData::new(
            "Vinedusk Training",
            SkillTree::Weapon,
            SkillLineName::Bow,
            vec![],
        )
        .with_skill_id(45494),
    ]
});
