// Auto-generated by datamine/generate_skills_rs.py - do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::unique::{MAJOR_BREACH, MAJOR_BRUTALITY, MAJOR_SORCERY};
use crate::domain::{
    SkillTree, DamageFlags, DotDamage, ExecuteScaling, HitDamage, Resource, SkillDamage, SkillData,
    SkillLineName,
};
use once_cell::sync::Lazy;

pub static BOW_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Acid Spray",
            "Arrow Spray",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40789)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::POISON | DamageFlags::AOE,
                    0.077476,
                    0.81349,
                )])
                .with_dots(vec![DotDamage::new(
                    4.0,
                    DamageFlags::POISON | DamageFlags::SINGLE_TARGET,
                    0.014118,
                    0.148235,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Arrow Barrage",
            "Volley",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40944)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            8.0,
            DamageFlags::physical_aoe(),
            0.019895,
            0.208896,
        )
        .with_delay(2.0)
        .with_interval(1.0)])),
        SkillData::new(
            "Arrow Spray",
            "Arrow Spray",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40765)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE,
            0.075,
            0.7875,
        )])),
        SkillData::new(
            "Ballista",
            "Rapid Fire",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Ultimate,
        )
        .with_skill_id(86620)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.0532809,
            0.559899,
        )])),
        SkillData::new(
            "Binding Vault",
            "Binding Vault",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Magicka,
        )
        .with_skill_id(40214974),
        SkillData::new(
            "Bombard",
            "Arrow Spray",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40777)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE,
            0.077476,
            0.81349,
        )])),
        SkillData::new(
            "Draining Shot",
            "Scatter Shot",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40883)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.06198,
            0.65079,
        )])),
        SkillData::new(
            "Endless Hail",
            "Volley",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40932)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            13.0,
            DamageFlags::physical_aoe(),
            0.015304,
            0.160689,
        )
        .with_delay(2.0)
        .with_interval(1.0)])),
        SkillData::new(
            "Fiery Vault",
            "Fiery Vault",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Magicka,
        )
        .with_skill_id(40214978),
        SkillData::new(
            "Focused Aim",
            "Snipe",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40907)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.106915,
            1.12261,
        )]))
        .with_bonuses(vec![MAJOR_BREACH.clone()]),
        SkillData::new(
            "Goading Vault",
            "Goading Vault",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Magicka,
        )
        .with_skill_id(40216674),
        SkillData::new(
            "Healing Vault",
            "Healing Vault",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Magicka,
        )
        .with_skill_id(40217777),
        SkillData::new(
            "Lethal Arrow",
            "Snipe",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40897)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::POISON | DamageFlags::SINGLE_TARGET,
            0.106915,
            1.12261,
        )])),
        SkillData::new(
            "Magnum Shot",
            "Scatter Shot",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40869)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.074376,
            0.780948,
        )])),
        SkillData::new(
            "Poison Arrow",
            "Poison Arrow",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40806)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::POISON | DamageFlags::SINGLE_TARGET,
                    0.05,
                    0.525,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::POISON | DamageFlags::SINGLE_TARGET,
                    0.015,
                    0.1575,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Poison Injection",
            "Poison Arrow",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40842)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::POISON | DamageFlags::SINGLE_TARGET,
                    0.05165,
                    0.542325,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::POISON | DamageFlags::SINGLE_TARGET,
                    0.015495,
                    0.162697,
                )
                .with_interval(2.0)]),
        )
        .with_execute(1.2, 0.5, ExecuteScaling::Linear),
        SkillData::new(
            "Rapid Fire",
            "Rapid Fire",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Ultimate,
        )
        .with_skill_id(86586)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.0861217,
            0.904012,
        )]))
        .with_channel_time(4.0),
        SkillData::new(
            "Scatter Shot",
            "Scatter Shot",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40858)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.06,
            0.63,
        )])),
        SkillData::new(
            "Snipe",
            "Snipe",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40892)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.1035,
            1.08675,
        )])),
        SkillData::new(
            "Sundering Vault",
            "Sundering Vault",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Magicka,
        )
        .with_skill_id(40214960),
        SkillData::new(
            "Toxic Barrage",
            "Rapid Fire",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Ultimate,
        )
        .with_skill_id(86603)
        .with_damage(SkillDamage::new().with_dots(vec![
            DotDamage::new(4.0, DamageFlags::poison_single(), 0.0860872, 0.904026),
            DotDamage::new(8.0, DamageFlags::poison_single(), 0.086083, 0.903875).with_delay(1.0),
        ]))
        .with_channel_time(4.0),
        SkillData::new(
            "Venom Arrow",
            "Poison Arrow",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40823)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::POISON | DamageFlags::SINGLE_TARGET,
                    0.05165,
                    0.542325,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::POISON | DamageFlags::SINGLE_TARGET,
                    0.015495,
                    0.162697,
                )
                .with_interval(2.0)]),
        )
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
        SkillData::new(
            "Volley",
            "Volley",
            SkillTree::Weapon,
            SkillLineName::Bow,
            Resource::Stamina,
        )
        .with_skill_id(40917)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            8.0,
            DamageFlags::physical_aoe(),
            0.014815,
            0.155556,
        )
        .with_delay(2.0)
        .with_interval(1.0)])),
    ]
});
