// Auto-generated by datamine/generate_passives_rs.py - do not edit manually.
// Manual overrides (bonuses) stored in generator script.
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, SkillTree, PassiveData,
    SkillLineName,
};
use once_cell::sync::Lazy;

pub static WARDEN_PASSIVES: Lazy<Vec<PassiveData>> = Lazy::new(|| {
    vec![
        PassiveData::new(
            "Advanced Species",
            SkillTree::Warden,
            SkillLineName::AnimalCompanions,
            vec![BonusData::new(
                "Advanced Species",
                BonusSource::Passive,
                BonusTrigger::AbilitySlottedCount,
                BonusValue::new("Advanced Species", BonusTarget::CriticalDamage, 0.05),
            )
            .with_skill_line_filter(SkillLineName::AnimalCompanions)],
        )
        .with_skill_id(86069),
        PassiveData::new(
            "Bond With Nature",
            SkillTree::Warden,
            SkillLineName::AnimalCompanions,
            vec![],
        )
        .with_skill_id(86065),
        PassiveData::new(
            "Flourish",
            SkillTree::Warden,
            SkillLineName::AnimalCompanions,
            vec![],
        )
        .with_skill_id(86067),
        PassiveData::new(
            "Savage Beast",
            SkillTree::Warden,
            SkillLineName::AnimalCompanions,
            vec![], // TODO: 4 ultimate generation,
        )
        .with_skill_id(86063),
        PassiveData::new(
            "Accelerated Growth",
            SkillTree::Warden,
            SkillLineName::GreenBalance,
            vec![],
        )
        .with_skill_id(85883),
        PassiveData::new(
            "Emerald Moss",
            SkillTree::Warden,
            SkillLineName::GreenBalance,
            vec![],
        )
        .with_skill_id(85877),
        PassiveData::new(
            "Maturation",
            SkillTree::Warden,
            SkillLineName::GreenBalance,
            vec![],
        )
        .with_skill_id(85881),
        PassiveData::new(
            "Nature's Gift",
            SkillTree::Warden,
            SkillLineName::GreenBalance,
            vec![],
        )
        .with_skill_id(85879),
        PassiveData::new(
            "Frozen Armor",
            SkillTree::Warden,
            SkillLineName::WintersEmbrace,
            vec![],
        )
        .with_skill_id(86190),
        PassiveData::new(
            "Glacial Presence",
            SkillTree::Warden,
            SkillLineName::WintersEmbrace,
            vec![
                BonusData::new(
                    "Glacial Presence 1",
                    BonusSource::Passive,
                    BonusTrigger::Passive,
                    BonusValue::new(
                        "Glacial Presence (Chance)",
                        BonusTarget::ChilledStatusEffectChance,
                        2.5,
                    ),
                ),
                BonusData::new(
                    "Glacial Presence 2",
                    BonusSource::Passive,
                    BonusTrigger::Passive,
                    BonusValue::new(
                        "Glacial Presence (Damage)",
                        BonusTarget::ChilledStatusEffectDamage,
                        105.0, // TODO: scales of WeaponOrSpellDamage
                    ),
                ),
            ],
        )
        .with_skill_id(86192),
        PassiveData::new(
            "Icy Aura",
            SkillTree::Warden,
            SkillLineName::WintersEmbrace,
            vec![],
        )
        .with_skill_id(86194),
        PassiveData::new(
            "Piercing Cold",
            SkillTree::Warden,
            SkillLineName::WintersEmbrace,
            vec![BonusData::new(
                "Piercing Cold",
                BonusSource::Passive,
                BonusTrigger::SkillLineSlotted,
                BonusValue::new("Piercing Cold", BonusTarget::FrostDamage, 0.15),
            )],
        )
        .with_skill_id(86196),
    ]
});
