// Auto-generated by datamine/generate_skills_rs.py — do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::unique::{
    MAJOR_BRUTALITY, MAJOR_PROPHECY, MAJOR_SAVAGERY, MAJOR_SORCERY,
};
use crate::domain::{
    BonusTrigger, ClassName, DamageFlags, DotDamage, HitDamage, Resource, SkillDamage, SkillData,
    SkillLineName,
};
use once_cell::sync::Lazy;

pub static MAGES_GUILD_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Balance",
            "Balance",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Stamina,
        )
        .with_skill_id(42278),
        SkillData::new(
            "Degeneration",
            "Entropy",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(42224)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.018782,
            0.19721,
        ).with_interval(2.0)]))
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
        SkillData::new(
            "Entropy",
            "Entropy",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(42207)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.018182,
            0.19091,
        ).with_interval(2.0)])),
        SkillData::new(
            "Equilibrium",
            "Equilibrium",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Stamina,
        )
        .with_skill_id(42251),
        SkillData::new(
            "Fire Rune",
            "Fire Rune",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(42305)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
            0.1,
            1.05,
        )])),
        SkillData::new(
            "Healing Contingency",
            "Healing Contingency",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(40240149),
        SkillData::new(
            "Ice Comet",
            "Meteor",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Ultimate,
        )
        .with_skill_id(42478)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FROST | DamageFlags::AOE | DamageFlags::MELEE,
                    0.198853,
                    2.08795,
                )])
                .with_dots(vec![DotDamage::new(
                    2.0,
                    DamageFlags::FROST | DamageFlags::AOE,
                    0.056815,
                    0.596557,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Inner Light",
            "Magelight",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(42430)
        .with_bonuses(vec![
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Magelight",
            "Magelight",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(42418)
        .with_bonuses(vec![
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Meteor",
            "Meteor",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Ultimate,
        )
        .with_skill_id(42467)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                    0.175,
                    1.8375,
                )])
                .with_dots(vec![DotDamage::new(
                    2.0,
                    DamageFlags::FLAME | DamageFlags::AOE,
                    0.05,
                    0.525,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Radiant Magelight",
            "Magelight",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(42455)
        .with_bonuses(vec![
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Scalding Rune",
            "Fire Rune",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(42349)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                    0.1033,
                    1.08465,
                )])
                .with_dots(vec![DotDamage::new(
                    20.0,
                    DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
                    0.01127,
                    0.11833,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Shooting Star",
            "Meteor",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Ultimate,
        )
        .with_skill_id(42492)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
                    0.18078,
                    1.89814,
                )])
                .with_dots(vec![DotDamage::new(
                    2.0,
                    DamageFlags::FLAME | DamageFlags::AOE,
                    0.05165,
                    0.542325,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Spell Symmetry",
            "Spell Symmetry",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Stamina,
        )
        .with_skill_id(42263),
        SkillData::new(
            "Structured Entropy",
            "Entropy",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(42240)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.018782,
            0.19721,
        ).with_interval(2.0)])),
        SkillData::new(
            "Ulfsild's Contingency",
            "Ulfsild's Contingency",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(40240148),
        SkillData::new(
            "Ulfsild's Contingency",
            "Ulfsild's Contingency",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(40222285),
        SkillData::new(
            "Ulfsild's Contingency",
            "Ulfsild's Contingency",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(40240150),
        SkillData::new(
            "Ulfsild's Contingency",
            "Ulfsild's Contingency",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(40222678),
        SkillData::new(
            "Ulfsild's Contingency",
            "Ulfsild's Contingency",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(40217528),
        SkillData::new(
            "Volcanic Rune",
            "Fire Rune",
            ClassName::Guild,
            SkillLineName::MagesGuild,
            Resource::Magicka,
        )
        .with_skill_id(42327)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::AOE | DamageFlags::MELEE,
            0.1033,
            1.08465,
        )])),
    ]
});
