// Auto-generated by datamine/generate_skills_rs.py — do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::{
    EMPOWER, MAJOR_BREACH, MAJOR_PROPHECY, MAJOR_SAVAGERY, MAJOR_VULNERABILITY,
};
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, ClassName, DamageFlags,
    DotDamage, HitDamage, Resource, SkillDamage, SkillData, SkillLineName,
};
use once_cell::sync::Lazy;

pub static NECROMANCER_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Agony Totem",
            "Bone Totem",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40118404)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            5.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.00282343,
            0.31544,
        ).with_interval(1.0)])),
        SkillData::new(
            "Beckoning Armor",
            "Bone Armor",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40118237),
        SkillData::new(
            "Bitter Harvest",
            "Bitter Harvest",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40115238),
        SkillData::new(
            "Bone Armor",
            "Bone Armor",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40115206),
        SkillData::new(
            "Bone Goliath Transformation",
            "Bone Goliath Transformation",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Ultimate,
        )
        .with_skill_id(40115001),
        SkillData::new(
            "Bone Totem",
            "Bone Totem",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40115093),
        SkillData::new(
            "Deaden Pain",
            "Bitter Harvest",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40118623),
        SkillData::new(
            "Death Scythe",
            "Death Scythe",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40115115)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.075,
            0.7875,
        )])),
        SkillData::new(
            "Empowering Grasp",
            "Grave Grasp",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40118352)
        .with_bonuses(vec![EMPOWER.clone().with_duration(5.0)]),
        SkillData::new(
            "Ghostly Embrace",
            "Grave Grasp",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40118308)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FROST | DamageFlags::AOE | DamageFlags::MELEE,
                    0.038737,
                    0.406744,
                )])
                .with_dots(vec![DotDamage::new(
                    4.0,
                    DamageFlags::FROST | DamageFlags::SINGLE_TARGET,
                    0.014118,
                    0.148235,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Grave Grasp",
            "Grave Grasp",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40115177),
        SkillData::new(
            "Hungry Scythe",
            "Death Scythe",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40118223)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        )])),
        SkillData::new(
            "Necrotic Potency",
            "Bitter Harvest",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40118639),
        SkillData::new(
            "Pummeling Goliath",
            "Bone Goliath Transformation",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Ultimate,
        )
        .with_skill_id(40118664)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        )])),
        SkillData::new(
            "Ravenous Goliath",
            "Bone Goliath Transformation",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Ultimate,
        )
        .with_skill_id(40118279)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.05,
            0.0,
        ).with_interval(1.0)])),
        SkillData::new(
            "Remote Totem",
            "Bone Totem",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40118380),
        SkillData::new(
            "Ruinous Scythe",
            "Ruinous Scythe",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Stamina,
        )
        .with_skill_id(40118226)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::BLEED | DamageFlags::AOE | DamageFlags::MELEE,
            0.077475,
            0.813488,
        )])),
        SkillData::new(
            "Summoner's Armor",
            "Bone Armor",
            ClassName::Necromancer,
            SkillLineName::BoneTyrant,
            Resource::Magicka,
        )
        .with_skill_id(40118244),
        SkillData::new(
            "Avid Boneyard",
            "Boneyard",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40117850)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FROST | DamageFlags::AOE | DamageFlags::MELEE,
                    0.1,
                    1.05,
                )])
                .with_dots(vec![DotDamage::new(
                    10.0,
                    DamageFlags::FROST | DamageFlags::AOE,
                    0.012521,
                    0.131473,
                )
                .with_interval(1.0)]),
        )
        .with_bonuses(vec![BonusData::new(
            "Avid Boneyard",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new(
                "Avid Boneyard Corpse",
                BonusTarget::WeaponAndSpellDamageFlat,
                300.0,
            ),
        )
        .with_duration(10.0)]),
        SkillData::new(
            "Blighted Blastbones",
            "Sacrificial Bones",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Stamina,
        )
        .with_skill_id(40117690)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::disease_aoe(), 0.12, 1.26).with_delay(2.5),
        ])),
        SkillData::new(
            "Boneyard",
            "Boneyard",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40115252)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FROST | DamageFlags::AOE | DamageFlags::MELEE,
                    0.1,
                    1.05,
                )])
                .with_dots(vec![DotDamage::new(
                    10.0,
                    DamageFlags::FROST | DamageFlags::AOE,
                    0.012121,
                    0.127273,
                )
                .with_interval(1.0)]),
        )
        .with_bonuses(vec![BonusData::new(
            "Boneyard",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new(
                "Boneyard Corpse",
                BonusTarget::WeaponAndSpellDamageFlat,
                300.0,
            ),
        )
        .with_duration(10.0)]),
        SkillData::new(
            "Detonating Siphon",
            "Shocking Siphon",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Stamina,
        )
        .with_skill_id(40118763)
        .with_damage(
            SkillDamage::new()
                .with_dots(vec![DotDamage::new(
                    12.0,
                    DamageFlags::shock_aoe(),
                    0.015495,
                    0.162697,
                )
                .with_interval(2.0)])
                .with_hits(vec![HitDamage::new(
                    DamageFlags::shock_aoe(),
                    0.05165,
                    0.542325,
                )
                .with_delay(12.0)]),
        )
        .with_bonuses(vec![
            BonusData::new(
                "Detonating Siphon",
                BonusSource::Buff,
                BonusTrigger::AbilitySlotted,
                BonusValue::new("Detonating Siphon", BonusTarget::Damage, 0.03),
            ),
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Flame Skull",
            "Flame Skull",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40114108)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.09,
            0.945,
        )]))
        .with_spammable(),
        SkillData::new(
            "Frozen Colossus",
            "Frozen Colossus",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Ultimate,
        )
        .with_skill_id(40122174)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::frost_aoe(), 0.15, 1.575),
            HitDamage::new(DamageFlags::frost_aoe(), 0.15, 1.575).with_delay(1.0),
            HitDamage::new(DamageFlags::frost_aoe(), 0.15, 1.575).with_delay(2.0),
        ]))
        .with_bonuses(vec![MAJOR_VULNERABILITY.clone().with_duration(12.0)]),
        SkillData::new(
            "Glacial Colossus",
            "Frozen Colossus",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Ultimate,
        )
        .with_skill_id(40122388)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::frost_aoe(), 0.15495, 1.62698),
            HitDamage::new(DamageFlags::frost_aoe(), 0.15495, 1.62698).with_delay(1.0),
            HitDamage::new(DamageFlags::frost_aoe(), 0.15495, 1.62698).with_delay(2.0),
        ]))
        .with_bonuses(vec![MAJOR_VULNERABILITY.clone().with_duration(12.0)]),
        SkillData::new(
            "Grave Lord's Sacrifice",
            "Sacrificial Bones",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40117749)
        .with_bonuses(vec![BonusData::new(
            "Grave Lord's Sacrifice",
            BonusSource::Buff,
            BonusTrigger::AbilitySlotted,
            BonusValue::new("Grave Lord's Sacrifice", BonusTarget::Damage, 0.15),
        )]),
        SkillData::new(
            "Mystic Siphon",
            "Shocking Siphon",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40118008)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            19.3,
            DamageFlags::SHOCK | DamageFlags::AOE,
            0.009182,
            0.096413,
        ).with_interval(0.7)]))
        .with_bonuses(vec![
            BonusData::new(
                "Mystic Siphon",
                BonusSource::Buff,
                BonusTrigger::AbilitySlotted,
                BonusValue::new("Mystic Siphon", BonusTarget::Damage, 0.03),
            ),
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Pestilent Colossus",
            "Frozen Colossus",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Ultimate,
        )
        .with_skill_id(40122395)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::disease_aoe(), 0.15495, 1.62698),
            HitDamage::new(DamageFlags::disease_aoe(), 0.15495, 1.62698).with_delay(1.0),
            HitDamage::new(DamageFlags::disease_aoe(), 0.15495, 1.62698).with_delay(2.0),
        ]))
        .with_bonuses(vec![MAJOR_VULNERABILITY.clone().with_duration(12.0)]),
        SkillData::new(
            "Ricochet Skull",
            "Flame Skull",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40117637)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::FLAME | DamageFlags::SINGLE_TARGET,
            0.09297,
            0.97619,
        )]))
        .with_spammable(),
        SkillData::new(
            "Sacrificial Bones",
            "Sacrificial Bones",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40114860)
        .with_bonuses(vec![BonusData::new(
            "Sacrificial Bones",
            BonusSource::Buff,
            BonusTrigger::AbilitySlotted,
            BonusValue::new("Sacrificial Bones", BonusTarget::Damage, 0.15),
        )]),
        SkillData::new(
            "Shocking Siphon",
            "Shocking Siphon",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40115924)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            19.3,
            DamageFlags::SHOCK | DamageFlags::AOE,
            0.008888,
            0.093333,
        ).with_interval(0.7)]))
        .with_bonuses(vec![
            BonusData::new(
                "Shocking Siphon",
                BonusSource::Buff,
                BonusTrigger::AbilitySlotted,
                BonusValue::new("Shocking Siphon", BonusTarget::Damage, 0.03),
            ),
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Skeletal Arcanist",
            "Skeletal Mage",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40118726)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET,
            0.02066,
            0.21693,
        )]))
        .with_bonuses(vec![BonusData::new(
            "Skeletal Arcanist",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new(
                "Arcanist Corpse",
                BonusTarget::WeaponAndSpellDamageFlat,
                300.0,
            ),
        )
        .with_duration(20.0)]),
        SkillData::new(
            "Skeletal Archer",
            "Skeletal Mage",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Stamina,
        )
        .with_skill_id(40118680)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::physical_single(),
            0.02066,
            0.21693,
        )
        .with_interval(2.0)
        .with_increase_per_tick(0.15)]))
        .with_bonuses(vec![BonusData::new(
            "Skeletal Archer",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new(
                "Archer Corpse",
                BonusTarget::WeaponAndSpellDamageFlat,
                300.0,
            ),
        )
        .with_duration(20.0)]),
        SkillData::new(
            "Skeletal Mage",
            "Skeletal Mage",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40114317)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET,
            0.02,
            0.21,
        )]))
        .with_bonuses(vec![BonusData::new(
            "Skeletal Mage",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new("Mage Corpse", BonusTarget::WeaponAndSpellDamageFlat, 300.0),
        )
        .with_duration(20.0)]),
        SkillData::new(
            "Unnerving Boneyard",
            "Boneyard",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Magicka,
        )
        .with_skill_id(40117805)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::FROST | DamageFlags::AOE | DamageFlags::MELEE,
                    0.1,
                    1.05,
                )])
                .with_dots(vec![DotDamage::new(
                    10.0,
                    DamageFlags::FROST | DamageFlags::AOE,
                    0.012521,
                    0.131473,
                )
                .with_interval(1.0)]),
        )
        .with_bonuses(vec![
            BonusData::new(
                "Unnerving Boneyard",
                BonusSource::Skill,
                BonusTrigger::Cast,
                BonusValue::new(
                    "Unnerving Boneyard Corpse",
                    BonusTarget::WeaponAndSpellDamageFlat,
                    300.0,
                ),
            )
            .with_duration(10.0),
            MAJOR_BREACH.clone(),
        ]),
        SkillData::new(
            "Venom Skull",
            "Flame Skull",
            ClassName::Necromancer,
            SkillLineName::GraveLord,
            Resource::Stamina,
        )
        .with_skill_id(40117624)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::POISON | DamageFlags::SINGLE_TARGET,
            0.09297,
            0.97619,
        )]))
        .with_spammable(),
        SkillData::new(
            "Blood Sacrifice",
            "Render Flesh",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40117888),
        SkillData::new(
            "Braided Tether",
            "Restoring Tether",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40118070),
        SkillData::new(
            "Enduring Undeath",
            "Life amid Death",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40118809),
        SkillData::new(
            "Expunge",
            "Expunge",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Stamina,
        )
        .with_skill_id(40115307),
        SkillData::new(
            "Expunge and Modify",
            "Expunge",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Stamina,
        )
        .with_skill_id(40117940),
        SkillData::new(
            "Hexproof",
            "Expunge",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Stamina,
        )
        .with_skill_id(40117919),
        SkillData::new(
            "Intensive Mender",
            "Spirit Mender",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40118840),
        SkillData::new(
            "Life amid Death",
            "Life amid Death",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40115315),
        SkillData::new(
            "Mortal Coil",
            "Restoring Tether",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40118122),
        SkillData::new(
            "Render Flesh",
            "Render Flesh",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40114196),
        SkillData::new(
            "Renewing Animation",
            "Reanimate",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Ultimate,
        )
        .with_skill_id(40118367),
        SkillData::new(
            "Renewing Undeath",
            "Life amid Death",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40118017),
        SkillData::new(
            "Resistant Flesh",
            "Render Flesh",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40117883),
        SkillData::new(
            "Restoring Tether",
            "Restoring Tether",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40115926),
        SkillData::new(
            "Spirit Guardian",
            "Spirit Mender",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40118912),
        SkillData::new(
            "Spirit Mender",
            "Spirit Mender",
            ClassName::Necromancer,
            SkillLineName::LivingDeath,
            Resource::Magicka,
        )
        .with_skill_id(40115710),
    ]
});
