// Auto-generated by datamine/generate_skills_rs.py — do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::{MAJOR_BRUTALITY, MAJOR_PROPHECY, MAJOR_SAVAGERY, MAJOR_SORCERY};
use crate::domain::{
    BonusData, BonusSource, BonusTarget, BonusTrigger, BonusValue, ClassName, DamageFlags,
    DotDamage, HitDamage, Resource, SkillDamage, SkillData, SkillLineName,
};
use once_cell::sync::Lazy;

pub static SORCERER_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Bound Aegis",
            "Bound Armor",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30445),
        SkillData::new(
            "Bound Armaments",
            "Bound Armor",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Stamina,
        )
        .with_skill_id(30432)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::physical_single(), 0.024, 0.252),
            HitDamage::new(DamageFlags::physical_single(), 0.024, 0.252),
            HitDamage::new(DamageFlags::physical_single(), 0.024, 0.252),
            HitDamage::new(DamageFlags::physical_single(), 0.024, 0.252),
            HitDamage::new(DamageFlags::physical_single(), 0.024, 0.252),
            HitDamage::new(DamageFlags::physical_single(), 0.024, 0.252),
            HitDamage::new(DamageFlags::physical_single(), 0.024, 0.252),
            HitDamage::new(DamageFlags::physical_single(), 0.024, 0.252),
        ]))
        .with_bonuses(vec![
            MAJOR_PROPHECY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
            MAJOR_SAVAGERY
                .clone()
                .with_trigger(BonusTrigger::AbilitySlotted),
        ]),
        SkillData::new(
            "Bound Armor",
            "Bound Armor",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30418),
        SkillData::new(
            "Conjured Ward",
            "Conjured Ward",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30463),
        SkillData::new(
            "Daedric Curse",
            "Daedric Curse",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30499)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_aoe(), 0.15, 1.575).with_delay(3.5),
        ])),
        SkillData::new(
            "Daedric Prey",
            "Daedric Curse",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30511)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_aoe(), 0.15495, 1.62698).with_delay(6.0),
        ])),
        SkillData::new(
            "Greater Storm Atronach",
            "Summon Storm Atronach",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Ultimate,
        )
        .with_skill_id(30575)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::SHOCK | DamageFlags::AOE | DamageFlags::MELEE,
                    0.1,
                    1.05,
                )])
                .with_dots(vec![DotDamage::new(
                    4.0,
                    DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET,
                    0.065,
                    0.6825,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Hardened Ward",
            "Conjured Ward",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30474),
        SkillData::new(
            "Haunting Curse",
            "Daedric Curse",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30523)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_aoe(), 0.10825, 1.13663).with_delay(3.5),
            HitDamage::new(DamageFlags::magic_aoe(), 0.10825, 1.13663).with_delay(6.5),
        ])),
        SkillData::new(
            "Regenerative Ward",
            "Conjured Ward",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30486),
        SkillData::new(
            "Summon Charged Atronach",
            "Summon Storm Atronach",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Ultimate,
        )
        .with_skill_id(30553)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::AOE | DamageFlags::MELEE,
                0.1,
                1.05,
            ),
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::AOE | DamageFlags::MELEE,
                0.1,
                1.05,
            ),
        ])),
        SkillData::new(
            "Summon Storm Atronach",
            "Summon Storm Atronach",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Ultimate,
        )
        .with_skill_id(30538)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::SHOCK | DamageFlags::AOE | DamageFlags::MELEE,
                    0.1,
                    1.05,
                )])
                .with_dots(vec![DotDamage::new(
                    4.0,
                    DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET,
                    0.05,
                    0.525,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Summon Twilight Matriarch",
            "Summon Winged Twilight",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30626)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.015495,
                0.162697,
            ),
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.015495,
                0.162697,
            ),
        ])),
        SkillData::new(
            "Summon Twilight Tormentor",
            "Summon Winged Twilight",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30598)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.02066,
                0.21693,
            ),
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.02066,
                0.21693,
            ),
        ])),
        SkillData::new(
            "Summon Unstable Clannfear",
            "Summon Unstable Familiar",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30657)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.015495,
                0.162697,
            ),
            HitDamage::new(
                DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
                0.015495,
                0.162697,
            ),
        ])),
        SkillData::new(
            "Summon Unstable Familiar",
            "Summon Unstable Familiar",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30641)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                    0.015,
                    0.1575,
                )])
                .with_dots(vec![DotDamage::new(
                    20.0,
                    DamageFlags::SHOCK | DamageFlags::AOE,
                    0.018182,
                    0.19091,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Summon Volatile Familiar",
            "Summon Unstable Familiar",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30674)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                    0.015495,
                    0.162697,
                )])
                .with_dots(vec![DotDamage::new(
                    20.0,
                    DamageFlags::SHOCK | DamageFlags::AOE,
                    0.018782,
                    0.19721,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Summon Winged Twilight",
            "Summon Winged Twilight",
            ClassName::Sorcerer,
            SkillLineName::DaedricSummoning,
            Resource::Magicka,
        )
        .with_skill_id(30587)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.015,
                0.1575,
            ),
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.015,
                0.1575,
            ),
        ])),
        SkillData::new(
            "Absorption Field",
            "Negate Magic",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Ultimate,
        )
        .with_skill_id(29881),
        SkillData::new(
            "Crystal Fragments",
            "Crystal Shard",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(47569)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                0.106915,
                1.12261,
            ),
            HitDamage::new(
                DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
                0.17748,
                1.86354,
            ),
        ]))
        .with_spammable(),
        SkillData::new(
            "Crystal Shard",
            "Crystal Shard",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(47552)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::MAGIC | DamageFlags::SINGLE_TARGET,
            0.1035,
            1.08675,
        )]))
        .with_spammable(),
        SkillData::new(
            "Crystal Weapon",
            "Crystal Shard",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Stamina,
        )
        .with_skill_id(47560)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.09297,
                0.976185,
            ),
            HitDamage::new(
                DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.037188,
                0.390474,
            ),
        ]))
        .with_spammable()
        .with_bonuses(vec![BonusData::new(
            "Crystal Weapon Debuff",
            BonusSource::Skill,
            BonusTrigger::Cast,
            BonusValue::new(
                "Crystal Weapon Debuff",
                BonusTarget::EnemyResistanceReduction,
                1000.0,
            ),
        )
        .with_duration(5.0)]),
        SkillData::new(
            "Daedric Mines",
            "Daedric Mines",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(29909)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_aoe(), 0.1, 1.05).with_delay(3.0),
        ])),
        SkillData::new(
            "Daedric Refuge",
            "Daedric Mines",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(29973),
        SkillData::new(
            "Daedric Tomb",
            "Daedric Mines",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(29939)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_aoe(), 0.1033, 1.08465).with_delay(3.0),
        ])),
        SkillData::new(
            "Dark Conversion",
            "Dark Exchange",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Stamina,
        )
        .with_skill_id(30072),
        SkillData::new(
            "Dark Deal",
            "Dark Exchange",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(30043),
        SkillData::new(
            "Dark Exchange",
            "Dark Exchange",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Stamina,
        )
        .with_skill_id(30012),
        SkillData::new(
            "Defensive Rune",
            "Rune Prison",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(30194),
        SkillData::new(
            "Encase",
            "Encase",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(30087),
        SkillData::new(
            "Negate Magic",
            "Negate Magic",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Ultimate,
        )
        .with_skill_id(29844),
        SkillData::new(
            "Rune Cage",
            "Rune Prison",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(30177)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::magic_single(), 0.077475, 0.813488).with_delay(5.0),
        ])),
        SkillData::new(
            "Rune Prison",
            "Rune Prison",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(30162),
        SkillData::new(
            "Shattering Spines",
            "Encase",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(30095)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::physical_aoe(), 0.077475, 0.813488).with_delay(1.5),
        ])),
        SkillData::new(
            "Suppression Field",
            "Negate Magic",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Ultimate,
        )
        .with_skill_id(29861)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            12.0,
            DamageFlags::MAGIC | DamageFlags::AOE,
            0.044697,
            0.46932,
        ).with_interval(1.0)])),
        SkillData::new(
            "Vibrant Shroud",
            "Encase",
            ClassName::Sorcerer,
            SkillLineName::DarkMagic,
            Resource::Magicka,
        )
        .with_skill_id(30107),
        SkillData::new(
            "Ball of Lightning",
            "Bolt Escape",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30224),
        SkillData::new(
            "Bolt Escape",
            "Bolt Escape",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30205),
        SkillData::new(
            "Boundless Storm",
            "Lightning Form",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30255)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            30.0,
            DamageFlags::SHOCK | DamageFlags::AOE,
            0.02066,
            0.21693,
        ).with_interval(2.0)])),
        SkillData::new(
            "Critical Surge",
            "Surge",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30406)
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
        SkillData::new(
            "Endless Fury",
            "Mages' Fury",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30343)
        .with_damage(
            SkillDamage::new().with_hits(vec![
                HitDamage::new(DamageFlags::shock_single(), 0.06198, 0.65079),
                HitDamage::new(DamageFlags::shock_single(), 0.09297, 0.976185)
                    .with_execute_threshold(0.20),
            ]),
        )
        .with_spammable(),
        SkillData::new(
            "Energy Overload",
            "Overload",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Ultimate,
        )
        .with_skill_id(30381)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET,
                0.1033,
                1.08465,
            ),
            HitDamage::new(DamageFlags::SHOCK | DamageFlags::AOE, 0.09297, 0.976185),
        ])),
        SkillData::new(
            "Hurricane",
            "Lightning Form",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Stamina,
        )
        .with_skill_id(30244)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::physical_aoe(),
            0.018782,
            0.19721,
        )
        .with_interval(2.0)
        .with_increase_per_tick(0.12)])),
        SkillData::new(
            "Lightning Flood",
            "Lightning Splash",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30302)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::SHOCK | DamageFlags::AOE | DamageFlags::MELEE,
                    0.12,
                    1.26,
                )])
                .with_dots(vec![DotDamage::new(
                    10.0,
                    DamageFlags::SHOCK | DamageFlags::AOE,
                    0.017905,
                    0.188006,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Lightning Form",
            "Lightning Form",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30235)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::SHOCK | DamageFlags::AOE,
            0.02,
            0.21,
        ).with_interval(2.0)])),
        SkillData::new(
            "Lightning Splash",
            "Lightning Splash",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30269)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::SHOCK | DamageFlags::AOE | DamageFlags::MELEE,
                    0.12,
                    1.26,
                )])
                .with_dots(vec![DotDamage::new(
                    10.0,
                    DamageFlags::SHOCK | DamageFlags::AOE,
                    0.013333,
                    0.14,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Liquid Lightning",
            "Lightning Splash",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30286)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::SHOCK | DamageFlags::AOE | DamageFlags::MELEE,
                    0.12,
                    1.26,
                )])
                .with_dots(vec![DotDamage::new(
                    15.0,
                    DamageFlags::SHOCK | DamageFlags::AOE,
                    0.013773,
                    0.14462,
                )
                .with_interval(1.0)]),
        ),
        SkillData::new(
            "Mages' Fury",
            "Mages' Fury",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30319)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::shock_single(), 0.06, 0.63),
            HitDamage::new(DamageFlags::shock_single(), 0.09, 0.945).with_execute_threshold(0.20),
        ]))
        .with_spammable(),
        SkillData::new(
            "Mages' Wrath",
            "Mages' Fury",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30331)
        .with_damage(
            SkillDamage::new().with_hits(vec![
                HitDamage::new(DamageFlags::shock_single(), 0.06198, 0.65079),
                HitDamage::new(DamageFlags::shock_aoe(), 0.09297, 0.976185)
                    .with_execute_threshold(0.20),
            ]),
        )
        .with_spammable(),
        SkillData::new(
            "Overload",
            "Overload",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Ultimate,
        )
        .with_skill_id(30354)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET, 0.1, 1.05),
            HitDamage::new(DamageFlags::SHOCK | DamageFlags::AOE, 0.09, 0.945),
        ])),
        SkillData::new(
            "Power Overload",
            "Overload",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Ultimate,
        )
        .with_skill_id(30366)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::SHOCK | DamageFlags::SINGLE_TARGET,
                0.11363,
                1.19311,
            ),
            HitDamage::new(DamageFlags::SHOCK | DamageFlags::AOE, 0.102267, 1.0738),
        ])),
        SkillData::new(
            "Power Surge",
            "Surge",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30396)
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
        SkillData::new(
            "Streak",
            "Bolt Escape",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30215)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::SHOCK | DamageFlags::AOE | DamageFlags::MELEE,
            0.06198,
            0.65079,
        )])),
        SkillData::new(
            "Surge",
            "Surge",
            ClassName::Sorcerer,
            SkillLineName::StormCalling,
            Resource::Magicka,
        )
        .with_skill_id(30390)
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
    ]
});
