// Auto-generated by datamine/generate_skills_rs.py - do not edit manually.
// Manual overrides (bonuses, execute, etc.) stored in generator script.
use crate::data::bonuses::unique::{MAJOR_BRUTALITY, MAJOR_SORCERY};
use crate::domain::{
    SkillTree, DamageFlags, DotDamage, ExecuteScaling, HitDamage, Resource, SkillDamage, SkillData,
    SkillLineName,
};
use once_cell::sync::Lazy;

pub static DUAL_WIELD_SKILLS: Lazy<Vec<SkillData>> = Lazy::new(|| {
    vec![
        SkillData::new(
            "Blade Cloak",
            "Blade Cloak",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40633)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::PHYSICAL | DamageFlags::AOE,
            0.018182,
            0.19091,
        ).with_interval(2.0)])),
        SkillData::new(
            "Blood Craze",
            "Twin Slashes",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40687)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                    0.025825,
                    0.271163,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
                    0.015495,
                    0.162697,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Bloodthirst",
            "Flurry",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40599)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::BLEED | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.0297,
            0.31184,
        )]))
        .with_spammable(),
        SkillData::new(
            "Deadly Cloak",
            "Blade Cloak",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40651)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            20.0,
            DamageFlags::PHYSICAL | DamageFlags::AOE,
            0.024417,
            0.256373,
        ).with_interval(2.0)])),
        SkillData::new(
            "Flurry",
            "Flurry",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40582)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.02875,
            0.301875,
        )]))
        .with_spammable(),
        SkillData::new(
            "Flying Blade",
            "Hidden Blade",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40628)
        .with_damage(SkillDamage::new().with_hits(vec![
            HitDamage::new(
                DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
                0.06198,
                0.65079,
            ),
            HitDamage::new(
                DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                0.09297,
                0.976185,
            ),
        ]))
        .with_bonuses(vec![
            MAJOR_BRUTALITY.clone().with_duration(40.0),
            MAJOR_SORCERY.clone().with_duration(40.0),
        ]),
        SkillData::new(
            "Hidden Blade",
            "Hidden Blade",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40610)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.06,
            0.63,
        )]))
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
        SkillData::new(
            "Lacerate",
            "Lacerate",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Ultimate,
        )
        .with_skill_id(86370)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            8.0,
            DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
            0.06,
            0.63,
        ).with_interval(2.0)])),
        SkillData::new(
            "Leashing Knife",
            "Leashing Knife",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Magicka,
        )
        .with_skill_id(40232112),
        SkillData::new(
            "Magic Knife",
            "Magic Knife",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Magicka,
        )
        .with_skill_id(40217473),
        SkillData::new(
            "Quick Cloak",
            "Blade Cloak",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40642)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            30.0,
            DamageFlags::PHYSICAL | DamageFlags::AOE,
            0.018782,
            0.19721,
        ).with_interval(2.0)])),
        SkillData::new(
            "Rapid Strikes",
            "Flurry",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40590)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
            0.0297,
            0.31184,
        )]))
        .with_spammable(),
        SkillData::new(
            "Rend",
            "Lacerate",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Ultimate,
        )
        .with_skill_id(86393)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            16.0,
            DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
            0.06198,
            0.65079,
        ).with_interval(2.0)])),
        SkillData::new(
            "Rending Slashes",
            "Twin Slashes",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40675)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                    0.03099,
                    0.325395,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
                    0.015495,
                    0.162697,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Shattering Knife",
            "Shattering Knife",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Magicka,
        )
        .with_skill_id(40217340),
        SkillData::new(
            "Shrouded Daggers",
            "Hidden Blade",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40619)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::SINGLE_TARGET,
            0.077475,
            0.813488,
        )]))
        .with_bonuses(vec![MAJOR_BRUTALITY.clone(), MAJOR_SORCERY.clone()]),
        SkillData::new(
            "Steel Tornado",
            "Whirlwind",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40744)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.077476,
            0.81349,
        )]))
        .with_spammable()
        .with_execute(0.33, 0.5, ExecuteScaling::Linear),
        SkillData::new(
            "Sundering Knife",
            "Sundering Knife",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Magicka,
        )
        .with_skill_id(40217872),
        SkillData::new(
            "Thrive in Chaos",
            "Lacerate",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Ultimate,
        )
        .with_skill_id(86410)
        .with_damage(SkillDamage::new().with_dots(vec![DotDamage::new(
            8.0,
            DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
            0.06198,
            0.65079,
        ).with_interval(2.0)])),
        SkillData::new(
            "Twin Slashes",
            "Twin Slashes",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40664)
        .with_damage(
            SkillDamage::new()
                .with_hits(vec![HitDamage::new(
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET | DamageFlags::MELEE,
                    0.025,
                    0.2625,
                )])
                .with_dots(vec![DotDamage::new(
                    18.0,
                    DamageFlags::BLEED | DamageFlags::SINGLE_TARGET,
                    0.015,
                    0.1575,
                )
                .with_interval(2.0)]),
        ),
        SkillData::new(
            "Whirling Blades",
            "Whirlwind",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40731)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.077476,
            0.81349,
        )]))
        .with_spammable()
        .with_execute(1.0, 0.5, ExecuteScaling::Linear),
        SkillData::new(
            "Whirlwind",
            "Whirlwind",
            SkillTree::Weapon,
            SkillLineName::DualWield,
            Resource::Stamina,
        )
        .with_skill_id(40714)
        .with_damage(SkillDamage::new().with_hits(vec![HitDamage::new(
            DamageFlags::PHYSICAL | DamageFlags::AOE | DamageFlags::MELEE,
            0.075,
            0.7875,
        )]))
        .with_spammable()
        .with_execute(0.33, 0.5, ExecuteScaling::Linear),
    ]
});
